"""
知识图谱模块 - URL路由配置

API命名规范：
- /api/student/* - 学生专用接口
- /api/teacher/* - 教师专用接口
"""

from django.urls import path
from . import views
from . import teacher_views

app_name = "knowledge"

urlpatterns = [
    # ============ 学生端 ============
    path(
        "api/student/knowledge-map", views.get_knowledge_map, name="get_knowledge_map"
    ),
    path(
        "api/student/knowledge-points/<int:point_id>",
        views.get_knowledge_point_detail,
        name="get_knowledge_point_detail",
    ),
    path(
        "api/student/knowledge-points/<int:point_id>/resources",
        views.knowledge_point_resources,
        name="knowledge_point_resources",
    ),
    path(
        "api/student/knowledge/points",
        views.get_knowledge_points_list,
        name="get_knowledge_points_list",
    ),
    path(
        "api/student/knowledge/relations",
        views.get_knowledge_relations,
        name="get_knowledge_relations",
    ),
    path(
        "api/student/knowledge/mastery",
        views.get_knowledge_mastery,
        name="get_knowledge_mastery",
    ),
    path(
        "api/student/knowledge/mastery/update",
        views.update_knowledge_mastery,
        name="update_knowledge_mastery",
    ),
    path(
        "api/student/knowledge/search", views.knowledge_search, name="knowledge_search"
    ),
    path(
        "api/student/resources",
        views.get_student_resources,
        name="get_student_resources",
    ),
    # ============ 教师端 ============
    # 资源管理
    path(
        "api/teacher/resources",
        teacher_views.resource_list,
        name="teacher_resource_list",
    ),
    path(
        "api/teacher/resources/create",
        teacher_views.resource_create,
        name="teacher_resource_create",
    ),
    path(
        "api/teacher/resources/upload",
        teacher_views.resource_upload,
        name="teacher_resource_upload",
    ),
    path(
        "api/teacher/resources/<int:resource_id>",
        teacher_views.resource_update,
        name="teacher_resource_update",
    ),
    path(
        "api/teacher/resources/<int:resource_id>/delete",
        teacher_views.resource_delete,
        name="teacher_resource_delete",
    ),
    path(
        "api/teacher/resources/<int:resource_id>/link-knowledge",
        teacher_views.resource_link_knowledge,
        name="teacher_resource_link_knowledge",
    ),
    # 题库管理
    path(
        "api/teacher/questions",
        teacher_views.question_list,
        name="teacher_question_list",
    ),
    path(
        "api/teacher/questions/create",
        teacher_views.question_create,
        name="teacher_question_create",
    ),
    path(
        "api/teacher/questions/batch-delete",
        teacher_views.question_batch_delete,
        name="teacher_question_batch_delete",
    ),
    path(
        "api/teacher/questions/import",
        teacher_views.question_import,
        name="teacher_question_import",
    ),
    path(
        "api/teacher/questions/export",
        teacher_views.question_export,
        name="teacher_question_export",
    ),
    path(
        "api/teacher/questions/template",
        teacher_views.question_template,
        name="teacher_question_template",
    ),
    path(
        "api/teacher/questions/<int:question_id>",
        teacher_views.question_detail,
        name="teacher_question_detail",
    ),
    path(
        "api/teacher/questions/<int:question_id>/update",
        teacher_views.question_update,
        name="teacher_question_update",
    ),
    path(
        "api/teacher/questions/<int:question_id>/delete",
        teacher_views.question_delete,
        name="teacher_question_delete",
    ),
    path(
        "api/teacher/questions/<int:question_id>/link-knowledge",
        teacher_views.question_link_knowledge,
        name="teacher_question_link_knowledge",
    ),
    # 知识图谱管理
    path(
        "api/teacher/knowledge-relations",
        teacher_views.knowledge_relation_list,
        name="teacher_knowledge_relation_list",
    ),
    path(
        "api/teacher/knowledge-relations/create",
        teacher_views.knowledge_relation_create,
        name="teacher_knowledge_relation_create",
    ),
    path(
        "api/teacher/knowledge-relations/<int:relation_id>",
        teacher_views.knowledge_relation_delete,
        name="teacher_knowledge_relation_delete",
    ),
    path(
        "api/teacher/knowledge-points",
        teacher_views.knowledge_point_list,
        name="teacher_knowledge_point_list",
    ),
    path(
        "api/teacher/knowledge-points/create",
        teacher_views.knowledge_point_create,
        name="teacher_knowledge_point_create",
    ),
    path(
        "api/teacher/knowledge-points/<int:point_id>",
        teacher_views.knowledge_point_update,
        name="teacher_knowledge_point_update",
    ),
    path(
        "api/teacher/knowledge-points/<int:point_id>/delete",
        teacher_views.knowledge_point_delete,
        name="teacher_knowledge_point_delete",
    ),
    path(
        "api/teacher/knowledge-map/import",
        teacher_views.knowledge_map_import,
        name="teacher_knowledge_map_import",
    ),
    path(
        "api/teacher/knowledge-map/save",
        teacher_views.knowledge_graph_save,
        name="teacher_knowledge_graph_save",
    ),
    path(
        "api/teacher/knowledge-map/publish",
        teacher_views.knowledge_map_publish,
        name="teacher_knowledge_map_publish",
    ),
    path(
        "api/teacher/knowledge-map/build-rag-index",
        teacher_views.knowledge_map_build_rag_index,
        name="teacher_knowledge_map_build_rag_index",
    ),
    path(
        "api/teacher/knowledge-map/export",
        teacher_views.knowledge_map_export,
        name="teacher_knowledge_map_export",
    ),
    path(
        "api/teacher/knowledge-map/template",
        teacher_views.knowledge_map_template,
        name="teacher_knowledge_map_template",
    ),
]
