# Generated by Django 6.0.1 on 2026-01-20 02:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


# 定义数据库迁移操作，Django 将按顺序执行以下变更
class Migration(migrations.Migration):

    # 标记为初始迁移，首次创建该应用的数据库表
    initial = True

    # 声明依赖的先前迁移版本
    dependencies = [
        ('courses', '0001_initial'),
    ]

    # 要执行的数据库操作列表
    operations = [
        # 创建数据表模型
        migrations.CreateModel(
            # 模型名称: KnowledgePoint
            name='KnowledgePoint',
            # 字段定义列表
            fields=[
                # id: ID (自增主键)
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # name: 知识点名称 (字符串字段)
                ('name', models.CharField(help_text='知识点的完整名称', max_length=200, verbose_name='知识点名称')),
                # description: 描述 (长文本字段)
                ('description', models.TextField(blank=True, help_text='知识点的详细描述', null=True, verbose_name='描述')),
                # chapter: 所属章节 (字符串字段)
                ('chapter', models.CharField(blank=True, max_length=100, null=True, verbose_name='所属章节')),
                # point_type: 类型 (字符串字段)
                ('point_type', models.CharField(choices=[('knowledge', '知识点'), ('skill', '技能'), ('concept', '概念')], default='knowledge', max_length=50, verbose_name='类型')),
                # order: 排序 (整数字段)
                ('order', models.IntegerField(default=0, help_text='用于控制知识点的显示顺序', verbose_name='排序')),
                # is_published: 是否发布 (布尔字段)
                ('is_published', models.BooleanField(default=False, help_text='发布后学生可见', verbose_name='是否发布')),
                # created_at: 创建时间 (日期时间字段)
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                # updated_at: 更新时间 (日期时间字段)
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            # 模型的 Meta 配置选项
            options={
                'verbose_name': '知识点',
                'verbose_name_plural': '知识点',
                'db_table': 'knowledge_points',
                'ordering': ['order', 'id'],
            },
        ),
        # 创建数据表模型
        migrations.CreateModel(
            # 模型名称: KnowledgeRelation
            name='KnowledgeRelation',
            # 字段定义列表
            fields=[
                # id: ID (自增主键)
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # relation_type: 关系类型 (字符串字段)
                ('relation_type', models.CharField(choices=[('prerequisite', '先修关系'), ('part_of', '包含关系'), ('related', '相关关系')], default='prerequisite', max_length=20, verbose_name='关系类型')),
            ],
            # 模型的 Meta 配置选项
            options={
                'verbose_name': '知识点关系',
                'verbose_name_plural': '知识点关系',
                'db_table': 'knowledge_relations',
            },
        ),
        # 创建数据表模型
        migrations.CreateModel(
            # 模型名称: ProfileSummary
            name='ProfileSummary',
            # 字段定义列表
            fields=[
                # id: ID (自增主键)
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # summary: 总体摘要 (长文本字段)
                ('summary', models.TextField(blank=True, null=True, verbose_name='总体摘要')),
                # weakness: 薄弱点 (长文本字段)
                ('weakness', models.TextField(blank=True, null=True, verbose_name='薄弱点')),
                # suggestion: 学习建议 (长文本字段)
                ('suggestion', models.TextField(blank=True, null=True, verbose_name='学习建议')),
                # generated_at: 生成时间 (日期时间字段)
                ('generated_at', models.DateTimeField(auto_now=True, verbose_name='生成时间')),
            ],
            # 模型的 Meta 配置选项
            options={
                'verbose_name': '画像摘要',
                'verbose_name_plural': '画像摘要',
                'db_table': 'profile_summaries',
            },
        ),
        # 创建数据表模型
        migrations.CreateModel(
            # 模型名称: Resource
            name='Resource',
            # 字段定义列表
            fields=[
                # id: ID (自增主键)
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # title: 资源标题 (字符串字段)
                ('title', models.CharField(max_length=300, verbose_name='资源标题')),
                # resource_type: 资源类型 (字符串字段)
                ('resource_type', models.CharField(choices=[('video', '视频'), ('document', '文档'), ('link', '外部链接'), ('exercise', '练习')], max_length=20, verbose_name='资源类型')),
                # file: 资源文件 (文件字段)
                ('file', models.FileField(blank=True, null=True, upload_to='resources/', verbose_name='资源文件')),
                # url: 资源链接 (URL 字段)
                ('url', models.URLField(blank=True, null=True, verbose_name='资源链接')),
                # description: 描述 (长文本字段)
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                # is_visible: 对学生可见 (布尔字段)
                ('is_visible', models.BooleanField(default=True, verbose_name='对学生可见')),
                # created_at: 创建时间 (日期时间字段)
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                # updated_at: 更新时间 (日期时间字段)
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            # 模型的 Meta 配置选项
            options={
                'verbose_name': '学习资源',
                'verbose_name_plural': '学习资源',
                'db_table': 'resources',
            },
        ),
        # 创建数据表模型
        migrations.CreateModel(
            # 模型名称: KnowledgeMastery
            name='KnowledgeMastery',
            # 字段定义列表
            fields=[
                # id: ID (自增主键)
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # mastery_rate: 掌握度 (精确小数字段)
                ('mastery_rate', models.DecimalField(decimal_places=3, default=0, help_text='0表示完全不掌握，1表示完全掌握', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='掌握度')),
                # updated_at: 更新时间 (日期时间字段)
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                # course: 课程 (外键关联)
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mastery_records', to='courses.course', verbose_name='课程')),
            ],
            # 模型的 Meta 配置选项
            options={
                'verbose_name': '知识掌握度',
                'verbose_name_plural': '知识掌握度',
                'db_table': 'knowledge_mastery',
            },
        ),
    ]
