# Generated by Django 6.0.1 on 2026-01-20 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


# 定义数据库迁移操作，Django 将按顺序执行以下变更
class Migration(migrations.Migration):

    # 标记为初始迁移，首次创建该应用的数据库表
    initial = True

    # 声明依赖的先前迁移版本
    dependencies = [
        ('courses', '0002_initial'),
        ('knowledge', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # 要执行的数据库操作列表
    operations = [
        # 添加新字段
        migrations.AddField(
            # 目标模型: knowledgemastery
            model_name='knowledgemastery',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mastery_records', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        # 添加新字段
        migrations.AddField(
            # 目标模型: knowledgepoint
            model_name='knowledgepoint',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_points', to='courses.course', verbose_name='所属课程'),
        ),
        # 添加新字段
        migrations.AddField(
            # 目标模型: knowledgemastery
            model_name='knowledgemastery',
            name='knowledge_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mastery_records', to='knowledge.knowledgepoint', verbose_name='知识点'),
        ),
        # 添加新字段
        migrations.AddField(
            # 目标模型: knowledgerelation
            model_name='knowledgerelation',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_relations', to='courses.course', verbose_name='所属课程'),
        ),
        # 添加新字段
        migrations.AddField(
            # 目标模型: knowledgerelation
            model_name='knowledgerelation',
            name='post_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_relations', to='knowledge.knowledgepoint', verbose_name='后续知识点'),
        ),
        # 添加新字段
        migrations.AddField(
            # 目标模型: knowledgerelation
            model_name='knowledgerelation',
            name='pre_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_relations', to='knowledge.knowledgepoint', verbose_name='前序知识点'),
        ),
        # 添加新字段
        migrations.AddField(
            # 目标模型: profilesummary
            model_name='profilesummary',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_summaries', to='courses.course', verbose_name='课程'),
        ),
        # 添加新字段
        migrations.AddField(
            # 目标模型: profilesummary
            model_name='profilesummary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_summaries', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        # 添加新字段
        migrations.AddField(
            # 目标模型: resource
            model_name='resource',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='courses.course', verbose_name='所属课程'),
        ),
        # 添加新字段
        migrations.AddField(
            # 目标模型: resource
            model_name='resource',
            name='knowledge_points',
            field=models.ManyToManyField(blank=True, related_name='resources', to='knowledge.knowledgepoint', verbose_name='关联知识点'),
        ),
        # 添加新字段
        migrations.AddField(
            # 目标模型: resource
            model_name='resource',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_resources', to=settings.AUTH_USER_MODEL, verbose_name='上传者'),
        ),
        # 修改联合唯一约束
        migrations.AlterUniqueTogether(
            name='knowledgemastery',
            unique_together={('user', 'knowledge_point')},
        ),
        # 修改联合唯一约束
        migrations.AlterUniqueTogether(
            name='knowledgerelation',
            unique_together={('pre_point', 'post_point')},
        ),
        # 修改联合唯一约束
        migrations.AlterUniqueTogether(
            name='profilesummary',
            unique_together={('user', 'course')},
        ),
    ]
