# Generated by Django 6.0.1 on 2026-01-21 09:07

from django.db import migrations, models


# 定义数据库迁移操作，Django 将按顺序执行以下变更
class Migration(migrations.Migration):

    # 声明依赖的先前迁移版本
    dependencies = [
        ('knowledge', '0002_initial'),
    ]

    # 要执行的数据库操作列表
    operations = [
        # 添加新字段
        migrations.AddField(
            # 目标模型: knowledgepoint
            model_name='knowledgepoint',
            name='category',
            field=models.CharField(blank=True, help_text='如：事实性、概念性、程序性、元认知', max_length=50, null=True, verbose_name='分类'),
        ),
        # 添加新字段
        migrations.AddField(
            # 目标模型: knowledgepoint
            model_name='knowledgepoint',
            name='cognitive_dimension',
            field=models.CharField(blank=True, help_text='如：记忆、理解、应用、分析、评价、创造', max_length=50, null=True, verbose_name='认知维度'),
        ),
        # 添加新字段
        migrations.AddField(
            # 目标模型: knowledgepoint
            model_name='knowledgepoint',
            name='level',
            field=models.IntegerField(default=1, help_text='知识点在层级结构中的级别（1-7）', verbose_name='层级'),
        ),
        # 添加新字段
        migrations.AddField(
            # 目标模型: knowledgepoint
            model_name='knowledgepoint',
            name='tags',
            field=models.CharField(blank=True, help_text='多个标签用分号分隔，如"重点;难点;考点"', max_length=200, null=True, verbose_name='标签'),
        ),
        # 添加新字段
        migrations.AddField(
            # 目标模型: knowledgepoint
            model_name='knowledgepoint',
            name='teaching_goal',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='教学目标'),
        ),
        # 修改字段属性
        migrations.AlterField(
            # 目标模型: knowledgepoint
            model_name='knowledgepoint',
            name='chapter',
            field=models.CharField(blank=True, help_text='层级路径，如"大数据技术基础 > Hadoop"', max_length=200, null=True, verbose_name='所属章节'),
        ),
    ]
