# Generated by Django 6.0.2 on 2026-02-14 06:26

from django.db import migrations, models


# 定义数据库迁移操作，Django 将按顺序执行以下变更
class Migration(migrations.Migration):

    # 声明依赖的先前迁移版本
    dependencies = [
        ('knowledge', '0003_knowledgepoint_category_and_more'),
    ]

    # 要执行的数据库操作列表
    operations = [
        # 添加新字段
        migrations.AddField(
            # 目标模型: resource
            model_name='resource',
            name='chapter_number',
            field=models.CharField(blank=True, help_text='资源对应的章节编号，如 1.1、1.2', max_length=20, null=True, verbose_name='章节编号'),
        ),
        # 添加新字段
        migrations.AddField(
            # 目标模型: resource
            model_name='resource',
            name='duration',
            field=models.IntegerField(blank=True, help_text='视频资源的时长，单位为秒', null=True, verbose_name='时长(秒)'),
        ),
        # 添加新字段
        migrations.AddField(
            # 目标模型: resource
            model_name='resource',
            name='sort_order',
            field=models.IntegerField(default=0, help_text='用于控制资源的显示顺序', verbose_name='排序序号'),
        ),
    ]
