# Generated by Django 6.0.2 on 2026-02-19 11:32

from django.db import migrations, models


# 定义数据库迁移操作，Django 将按顺序执行以下变更
class Migration(migrations.Migration):

    # 声明依赖的先前迁移版本
    dependencies = [
        ('knowledge', '0004_resource_chapter_number_resource_duration_and_more'),
    ]

    # 要执行的数据库操作列表
    operations = [
        # 修改字段属性
        migrations.AlterField(
            # 目标模型: knowledgerelation
            model_name='knowledgerelation',
            name='relation_type',
            field=models.CharField(choices=[('prerequisite', '先修关系'), ('part_of', '包含关系'), ('related', '相关关系'), ('includes', '层级包含')], default='prerequisite', max_length=20, verbose_name='关系类型'),
        ),
    ]
