# Generated by Codex on 2026-05-13

from django.db import migrations, models


class Migration(migrations.Migration):
    """Add resource processing status fields for teacher import visibility."""

    dependencies = [
        ("knowledge", "0006_knowledgepoint_introduction_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="processing_status",
            field=models.CharField(
                choices=[
                    ("uploaded", "已上传"),
                    ("running", "处理中"),
                    ("ready", "可用"),
                    ("failed", "处理失败"),
                ],
                default="uploaded",
                help_text="资源导入、解析或索引构建状态：uploaded/running/ready/failed",
                max_length=20,
                verbose_name="处理状态",
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="processing_message",
            field=models.TextField(
                blank=True,
                help_text="记录资源处理失败原因或最近一次导入说明",
                null=True,
                verbose_name="处理说明",
            ),
        ),
    ]
