# Generated by Django 6.0.1 on 2026-01-20 02:24

from django.db import migrations, models


# 定义数据库迁移操作，Django 将按顺序执行以下变更
class Migration(migrations.Migration):

    # 标记为初始迁移，首次创建该应用的数据库表
    initial = True

    # 声明依赖的先前迁移版本
    dependencies = [
    ]

    # 要执行的数据库操作列表
    operations = [
        # 创建数据表模型
        migrations.CreateModel(
            # 模型名称: AbilityScore
            name='AbilityScore',
            # 字段定义列表
            fields=[
                # id: ID (自增主键)
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # scores: 能力维度得分 (JSON 数据字段)
                ('scores', models.JSONField(default=dict, help_text='格式: {"逻辑推理": 85, "抽象思维": 72, ...}', verbose_name='能力维度得分')),
                # created_at: 创建时间 (日期时间字段)
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                # updated_at: 更新时间 (日期时间字段)
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            # 模型的 Meta 配置选项
            options={
                'verbose_name': '能力评分',
                'verbose_name_plural': '能力评分',
                'db_table': 'ability_scores',
            },
        ),
        # 创建数据表模型
        migrations.CreateModel(
            # 模型名称: Assessment
            name='Assessment',
            # 字段定义列表
            fields=[
                # id: ID (自增主键)
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # title: 测评标题 (字符串字段)
                ('title', models.CharField(max_length=200, verbose_name='测评标题')),
                # assessment_type: 测评类型 (字符串字段)
                ('assessment_type', models.CharField(choices=[('knowledge', '知识掌握度测评'), ('ability', '学习能力评估'), ('habit', '学习习惯问卷')], max_length=20, verbose_name='测评类型')),
                # description: 描述 (长文本字段)
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                # is_active: 是否启用 (布尔字段)
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                # created_at: 创建时间 (日期时间字段)
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            # 模型的 Meta 配置选项
            options={
                'verbose_name': '测评',
                'verbose_name_plural': '测评',
                'db_table': 'assessments',
            },
        ),
        # 创建数据表模型
        migrations.CreateModel(
            # 模型名称: AssessmentQuestion
            name='AssessmentQuestion',
            # 字段定义列表
            fields=[
                # id: ID (自增主键)
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # order: 排序 (整数字段)
                ('order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            # 模型的 Meta 配置选项
            options={
                'db_table': 'assessment_questions',
                'ordering': ['order'],
            },
        ),
        # 创建数据表模型
        migrations.CreateModel(
            # 模型名称: AssessmentResult
            name='AssessmentResult',
            # 字段定义列表
            fields=[
                # id: ID (自增主键)
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # answers: 答案 (JSON 数据字段)
                ('answers', models.JSONField(default=dict, help_text='格式: {question_id: answer, ...}', verbose_name='答案')),
                # score: 得分 (精确小数字段)
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='得分')),
                # result_data: 结果数据 (JSON 数据字段)
                ('result_data', models.JSONField(default=dict, verbose_name='结果数据')),
                # completed_at: 完成时间 (日期时间字段)
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='完成时间')),
            ],
            # 模型的 Meta 配置选项
            options={
                'verbose_name': '测评结果',
                'verbose_name_plural': '测评结果',
                'db_table': 'assessment_results',
            },
        ),
        # 创建数据表模型
        migrations.CreateModel(
            # 模型名称: AssessmentStatus
            name='AssessmentStatus',
            # 字段定义列表
            fields=[
                # id: ID (自增主键)
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # knowledge_done: 知识测评完成 (布尔字段)
                ('knowledge_done', models.BooleanField(default=False, verbose_name='知识测评完成')),
                # ability_done: 能力测评完成 (布尔字段)
                ('ability_done', models.BooleanField(default=False, verbose_name='能力测评完成')),
                # habit_done: 习惯问卷完成 (布尔字段)
                ('habit_done', models.BooleanField(default=False, verbose_name='习惯问卷完成')),
            ],
            # 模型的 Meta 配置选项
            options={
                'verbose_name': '测评状态',
                'verbose_name_plural': '测评状态',
                'db_table': 'assessment_status',
            },
        ),
        # 创建数据表模型
        migrations.CreateModel(
            # 模型名称: Question
            name='Question',
            # 字段定义列表
            fields=[
                # id: ID (自增主键)
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # content: 题目内容 (长文本字段)
                ('content', models.TextField(help_text='题目的完整描述', verbose_name='题目内容')),
                # question_type: 题目类型 (字符串字段)
                ('question_type', models.CharField(choices=[('single_choice', '单选题'), ('multiple_choice', '多选题'), ('true_false', '判断题'), ('fill_blank', '填空题'), ('short_answer', '简答题'), ('code', '编程题')], max_length=20, verbose_name='题目类型')),
                # options: 选项 (JSON 数据字段)
                ('options', models.JSONField(blank=True, default=list, help_text='格式: [{"label": "A", "content": "选项内容"}, ...]', verbose_name='选项')),
                # answer: 正确答案 (JSON 数据字段)
                ('answer', models.JSONField(default=dict, help_text='格式: {"answer": "A"} 或 {"answers": ["A", "B"]}', verbose_name='正确答案')),
                # analysis: 解析 (长文本字段)
                ('analysis', models.TextField(blank=True, help_text='题目的详细解析', null=True, verbose_name='解析')),
                # difficulty: 难度 (字符串字段)
                ('difficulty', models.CharField(choices=[('easy', '简单'), ('medium', '中等'), ('hard', '困难')], default='medium', max_length=20, verbose_name='难度')),
                # score: 默认分值 (精确小数字段)
                ('score', models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='默认分值')),
                # created_at: 创建时间 (日期时间字段)
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                # updated_at: 更新时间 (日期时间字段)
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            # 模型的 Meta 配置选项
            options={
                'verbose_name': '题目',
                'verbose_name_plural': '题目',
                'db_table': 'questions',
            },
        ),
        # 创建数据表模型
        migrations.CreateModel(
            # 模型名称: SurveyQuestion
            name='SurveyQuestion',
            # 字段定义列表
            fields=[
                # id: ID (自增主键)
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # text: 题目文本 (长文本字段)
                ('text', models.TextField(help_text='问卷题目的完整描述', verbose_name='题目文本')),
                # question_type: 题目类型 (字符串字段)
                ('question_type', models.CharField(choices=[('single_select', '单选'), ('multi_select', '多选'), ('scale', '量表'), ('text', '文本')], max_length=20, verbose_name='题目类型')),
                # options: 选项 (JSON 数据字段)
                ('options', models.JSONField(default=list, help_text='格式: [{"value": "A", "label": "选项文本", "score": 1}, ...]', verbose_name='选项')),
                # order: 排序 (整数字段)
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                # is_global: 全局通用 (布尔字段)
                ('is_global', models.BooleanField(default=True, help_text='全局通用的题目适用于所有课程', verbose_name='全局通用')),
            ],
            # 模型的 Meta 配置选项
            options={
                'verbose_name': '问卷题目',
                'verbose_name_plural': '问卷题目',
                'db_table': 'survey_questions',
                'ordering': ['order'],
            },
        ),
    ]
