# Generated by Django 6.0.1 on 2026-01-20 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


# 定义数据库迁移操作，Django 将按顺序执行以下变更
class Migration(migrations.Migration):

    # 标记为初始迁移，首次创建该应用的数据库表
    initial = True

    # 声明依赖的先前迁移版本
    dependencies = [
        ('assessments', '0002_initial'),
        ('courses', '0001_initial'),
        ('knowledge', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # 要执行的数据库操作列表
    operations = [
        # 添加新字段
        migrations.AddField(
            # 目标模型: abilityscore
            model_name='abilityscore',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ability_scores', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        # 添加新字段
        migrations.AddField(
            # 目标模型: assessment
            model_name='assessment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='courses.course', verbose_name='所属课程'),
        ),
        # 添加新字段
        migrations.AddField(
            # 目标模型: assessmentquestion
            model_name='assessmentquestion',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.assessment'),
        ),
        # 添加新字段
        migrations.AddField(
            # 目标模型: assessmentresult
            model_name='assessmentresult',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='assessments.assessment', verbose_name='测评'),
        ),
        # 添加新字段
        migrations.AddField(
            # 目标模型: assessmentresult
            model_name='assessmentresult',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_results', to='courses.course', verbose_name='课程'),
        ),
        # 添加新字段
        migrations.AddField(
            # 目标模型: assessmentresult
            model_name='assessmentresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_results', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        # 添加新字段
        migrations.AddField(
            # 目标模型: assessmentstatus
            model_name='assessmentstatus',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_status', to='courses.course', verbose_name='课程'),
        ),
        # 添加新字段
        migrations.AddField(
            # 目标模型: assessmentstatus
            model_name='assessmentstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_status', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        # 添加新字段
        migrations.AddField(
            # 目标模型: question
            model_name='question',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.course', verbose_name='所属课程'),
        ),
        # 添加新字段
        migrations.AddField(
            # 目标模型: question
            model_name='question',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_questions', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        # 添加新字段
        migrations.AddField(
            # 目标模型: question
            model_name='question',
            name='knowledge_points',
            field=models.ManyToManyField(blank=True, related_name='questions', to='knowledge.knowledgepoint', verbose_name='关联知识点'),
        ),
        # 添加新字段
        migrations.AddField(
            # 目标模型: assessmentquestion
            model_name='assessmentquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.question'),
        ),
        # 添加新字段
        migrations.AddField(
            # 目标模型: assessment
            model_name='assessment',
            name='questions',
            field=models.ManyToManyField(related_name='assessments', through='assessments.AssessmentQuestion', to='assessments.question', verbose_name='题目'),
        ),
        # 添加新字段
        migrations.AddField(
            # 目标模型: surveyquestion
            model_name='surveyquestion',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_questions', to='courses.course', verbose_name='所属课程'),
        ),
        # 修改联合唯一约束
        migrations.AlterUniqueTogether(
            name='abilityscore',
            unique_together={('user', 'course')},
        ),
        # 修改联合唯一约束
        migrations.AlterUniqueTogether(
            name='assessmentresult',
            unique_together={('user', 'assessment')},
        ),
        # 修改联合唯一约束
        migrations.AlterUniqueTogether(
            name='assessmentstatus',
            unique_together={('user', 'course')},
        ),
    ]
