# Generated by Django 6.0.1 on 2026-01-21 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


# 定义数据库迁移操作，Django 将按顺序执行以下变更
class Migration(migrations.Migration):

    # 声明依赖的先前迁移版本
    dependencies = [
        ('assessments', '0003_initial'),
        ('courses', '0003_alter_class_options_class_description_and_more'),
        ('knowledge', '0003_knowledgepoint_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # 要执行的数据库操作列表
    operations = [
        # 修改模型元数据选项
        migrations.AlterModelOptions(
            name='surveyquestion',
            options={'ordering': ['survey_type', 'order'], 'verbose_name': '问卷题目', 'verbose_name_plural': '问卷题目'},
        ),
        # 添加新字段
        migrations.AddField(
            # 目标模型: question
            model_name='question',
            name='for_initial_assessment',
            field=models.BooleanField(default=False, help_text='是否可用于初始评测随机抽题', verbose_name='用于初始评测'),
        ),
        # 添加新字段
        migrations.AddField(
            # 目标模型: question
            model_name='question',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='是否在题库中对学生可见', verbose_name='对学生可见'),
        ),
        # 添加新字段
        migrations.AddField(
            # 目标模型: surveyquestion
            model_name='surveyquestion',
            name='dimension',
            field=models.CharField(blank=True, help_text='该题测量的能力维度，如"逻辑推理"、"抽象思维"等', max_length=50, null=True, verbose_name='能力维度'),
        ),
        # 添加新字段
        migrations.AddField(
            # 目标模型: surveyquestion
            model_name='surveyquestion',
            name='is_required',
            field=models.BooleanField(default=True, verbose_name='是否必答'),
        ),
        # 添加新字段
        migrations.AddField(
            # 目标模型: surveyquestion
            model_name='surveyquestion',
            name='survey_type',
            field=models.CharField(choices=[('ability', '智力量表'), ('habit', '学习偏好问卷')], default='habit', max_length=20, verbose_name='问卷类型'),
        ),
        # 创建数据表模型
        migrations.CreateModel(
            # 模型名称: AnswerHistory
            name='AnswerHistory',
            # 字段定义列表
            fields=[
                # id: ID (自增主键)
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # student_answer: 学生答案 (JSON 数据字段)
                ('student_answer', models.JSONField(default=dict, verbose_name='学生答案')),
                # correct_answer: 正确答案 (JSON 数据字段)
                ('correct_answer', models.JSONField(default=dict, verbose_name='正确答案')),
                # is_correct: 是否正确 (布尔字段)
                ('is_correct', models.BooleanField(default=False, verbose_name='是否正确')),
                # score: 得分 (精确小数字段)
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='得分')),
                # source: 来源 (字符串字段)
                ('source', models.CharField(default='practice', help_text='答题来源：initial（初始评测）, exam（考试）, practice（练习）', max_length=50, verbose_name='来源')),
                # exam_id: 考试ID (整数字段)
                ('exam_id', models.IntegerField(blank=True, null=True, verbose_name='考试ID')),
                # answered_at: 答题时间 (日期时间字段)
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='答题时间')),
                # course: 课程 (外键关联)
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_histories', to='courses.course', verbose_name='课程')),
                # knowledge_point: 知识点 (外键关联)
                ('knowledge_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answer_histories', to='knowledge.knowledgepoint', verbose_name='知识点')),
                # question: 题目 (外键关联)
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_histories', to='assessments.question', verbose_name='题目')),
                # user: 用户 (外键关联)
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_histories', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            # 模型的 Meta 配置选项
            options={
                'verbose_name': '答题历史',
                'verbose_name_plural': '答题历史',
                'db_table': 'answer_histories',
                'ordering': ['-answered_at'],
            },
        ),
        # 创建数据表模型
        migrations.CreateModel(
            # 模型名称: ProfileHistory
            name='ProfileHistory',
            # 字段定义列表
            fields=[
                # id: ID (自增主键)
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # knowledge_mastery: 知识掌握度 (JSON 数据字段)
                ('knowledge_mastery', models.JSONField(default=dict, help_text='格式: {"知识点ID": 掌握度, ...}', verbose_name='知识掌握度')),
                # ability_scores: 能力得分 (JSON 数据字段)
                ('ability_scores', models.JSONField(default=dict, help_text='格式: {"能力维度": 得分, ...}', verbose_name='能力得分')),
                # habit_preferences: 学习偏好 (JSON 数据字段)
                ('habit_preferences', models.JSONField(default=dict, verbose_name='学习偏好')),
                # summary: 画像摘要 (长文本字段)
                ('summary', models.TextField(blank=True, null=True, verbose_name='画像摘要')),
                # update_reason: 更新原因 (字符串字段)
                ('update_reason', models.CharField(default='manual', help_text='更新原因：initial（初始评测）, exam（考试完成）, manual（手动更新）', max_length=100, verbose_name='更新原因')),
                # external_mastery: 外部掌握情况 (JSON 数据字段)
                ('external_mastery', models.JSONField(blank=True, default=dict, help_text='预留字段：外部接口返回的掌握情况分析', null=True, verbose_name='外部掌握情况')),
                # created_at: 创建时间 (日期时间字段)
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                # course: 课程 (外键关联)
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_histories', to='courses.course', verbose_name='课程')),
                # user: 用户 (外键关联)
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_histories', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            # 模型的 Meta 配置选项
            options={
                'verbose_name': '画像历史',
                'verbose_name_plural': '画像历史',
                'db_table': 'profile_histories',
                'ordering': ['-created_at'],
            },
        ),
        # 创建数据表模型
        migrations.CreateModel(
            # 模型名称: SurveyResult
            name='SurveyResult',
            # 字段定义列表
            fields=[
                # id: ID (自增主键)
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # survey_type: 问卷类型 (字符串字段)
                ('survey_type', models.CharField(choices=[('ability', '智力量表'), ('habit', '学习偏好问卷')], max_length=20, verbose_name='问卷类型')),
                # answers: 答案 (JSON 数据字段)
                ('answers', models.JSONField(default=dict, help_text='格式: {question_id: answer, ...}', verbose_name='答案')),
                # result: 结果 (JSON 数据字段)
                ('result', models.JSONField(default=dict, help_text='根据答案计算出的结果，如能力得分或偏好设置', verbose_name='结果')),
                # version: 版本号 (整数字段)
                ('version', models.IntegerField(default=1, verbose_name='版本号')),
                # is_current: 是否当前版本 (布尔字段)
                ('is_current', models.BooleanField(default=True, verbose_name='是否当前版本')),
                # completed_at: 完成时间 (日期时间字段)
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='完成时间')),
                # user: 用户 (外键关联)
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_results', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            # 模型的 Meta 配置选项
            options={
                'verbose_name': '问卷结果',
                'verbose_name_plural': '问卷结果',
                'db_table': 'survey_results',
                'ordering': ['-completed_at'],
            },
        ),
    ]
