# Generated by Django 6.0.2 on 2026-02-14 06:26

from django.db import migrations, models


# 定义数据库迁移操作，Django 将按顺序执行以下变更
class Migration(migrations.Migration):

    # 声明依赖的先前迁移版本
    dependencies = [
        ('assessments', '0004_alter_surveyquestion_options_and_more'),
    ]

    # 要执行的数据库操作列表
    operations = [
        # 添加新字段
        migrations.AddField(
            # 目标模型: question
            model_name='question',
            name='chapter',
            field=models.CharField(blank=True, help_text='题目所属的章节或目录信息', max_length=200, null=True, verbose_name='所属章节'),
        ),
        # 添加新字段
        migrations.AddField(
            # 目标模型: question
            model_name='question',
            name='suggested_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='从试卷导入时的建议分数', max_digits=5, null=True, verbose_name='建议分数'),
        ),
    ]
