# Generated by Django 6.0.2 on 2026-03-02 02:29

from django.db import migrations, models


# 定义数据库迁移操作，Django 将按顺序执行以下变更
class Migration(migrations.Migration):

    # 声明依赖的先前迁移版本
    dependencies = [
        ('assessments', '0005_question_chapter_question_suggested_score'),
    ]

    # 要执行的数据库操作列表
    operations = [
        # 添加新字段
        migrations.AddField(
            # 目标模型: assessmentstatus
            model_name='assessmentstatus',
            name='generating',
            field=models.BooleanField(default=False, verbose_name='正在生成中'),
        ),
        # 添加新字段
        migrations.AddField(
            # 目标模型: assessmentstatus
            model_name='assessmentstatus',
            name='generation_error',
            field=models.TextField(blank=True, null=True, verbose_name='生成错误信息'),
        ),
    ]
