#!/user/bin/env python
# -*- coding: UTF-8 -*-
'''
student1 大数据学习状态内置预置数据。
@Project : wisdom-edu
@File : demo_student1_snapshot_parse.py
@Author : Qintsg
@Date : 2026-05-13 13:36
'''

from __future__ import annotations

from tools.demo_student1_snapshot_types import (
    DesktopSnapshot,
    FeedbackReportSnapshot,
    PathNodeSnapshot,
    QuestionSnapshot,
)


PRESET_VERSION = "2026-05-14-student1-big-data-inline"


INLINE_QUESTION_PAYLOADS = [{'order': 1,
  'content': "大数据的四个V特征中，'Variety'指的是数据的什么性质？",
  'question_type': 'single_choice',
  'options': [{'label': 'A', 'content': '数据量大'},
              {'label': 'B', 'content': '数据多样性'},
              {'label': 'C', 'content': '数据处理速度快'},
              {'label': 'D', 'content': '数据价值高'}],
  'student_answer': 'B',
  'correct_answer': 'B',
  'student_answer_display': 'B',
  'correct_answer_display': 'B',
  'is_correct': True,
  'analysis': "'Variety'是大数据的四个V特征之一，指数据来源的多样性和形式的复杂性。",
  'knowledge_point_names': [],
  'difficulty': 'medium',
  'score': 2.0},
 {'order': 2,
  'content': '第三次信息化浪潮的发生标志是以下哪种技术的普及：',
  'question_type': 'single_choice',
  'options': [{'label': 'A', 'content': '个人计算机'},
              {'label': 'B', 'content': '物联网、云计算和大数据'},
              {'label': 'C', 'content': 'CPU'},
              {'label': 'D', 'content': '互联网'}],
  'student_answer': 'A',
  'correct_answer': 'B',
  'student_answer_display': 'A',
  'correct_answer_display': 'B',
  'is_correct': False,
  'analysis': '',
  'knowledge_point_names': [],
  'difficulty': 'easy',
  'score': 2.0},
 {'order': 3,
  'content': '下面哪个选项属于大数据技术的“数据存储和管理”技术层面的功能?( )',
  'question_type': 'single_choice',
  'options': [{'label': 'A', 'content': '利用分布式文件系统、数据仓库、关系数据库等实现对结构化、半结构化和非结构化海量数据的存储和管理'},
              {'label': 'B', 'content': '利用分布式并行编程模型和计算框架，结合机器学习和数据挖掘算法，实现对海量数据的处理和分析'},
              {'label': 'C', 'content': '构建隐私数据保护体系和数据安全体系，有效保护个人隐私和数据安全'},
              {'label': 'D', 'content': '把实时采集的数据作为流计算系统的输入，进行实时处理分析'}],
  'student_answer': 'A',
  'correct_answer': 'A',
  'student_answer_display': 'A',
  'correct_answer_display': 'A',
  'is_correct': True,
  'analysis': '',
  'knowledge_point_names': [],
  'difficulty': 'easy',
  'score': 2.0},
 {'order': 4,
  'content': '以下哪个不是大数据的典型应用场景？',
  'question_type': 'single_choice',
  'options': [{'label': 'A', 'content': '市场趋势预测'},
              {'label': 'B', 'content': '库存管理'},
              {'label': 'C', 'content': '文档编辑'},
              {'label': 'D', 'content': '金融风险管理'}],
  'student_answer': 'C',
  'correct_answer': 'C',
  'student_answer_display': 'C',
  'correct_answer_display': 'C',
  'is_correct': True,
  'analysis': '文档编辑通常由办公软件完成，不属于大数据典型应用场景。',
  'knowledge_point_names': [],
  'difficulty': 'medium',
  'score': 2.0},
 {'order': 5,
  'content': '以下哪一项不属于Hadoop可以运行的模式（ ）。',
  'question_type': 'single_choice',
  'options': [{'label': 'A', 'content': '单机（本地）模式'},
              {'label': 'B', 'content': '伪分布式模式'},
              {'label': 'C', 'content': '互联模式'},
              {'label': 'D', 'content': '分布式模式'}],
  'student_answer': 'C',
  'correct_answer': 'C',
  'student_answer_display': 'C',
  'correct_answer_display': 'C',
  'is_correct': True,
  'analysis': '',
  'knowledge_point_names': [],
  'difficulty': 'easy',
  'score': 2.0},
 {'order': 6,
  'content': 'Hadoop2.0引入了资源管理框架（ ），来是实现Hadoop1.0中MapReduce在扩展性和多框架支持等方面的不足。',
  'question_type': 'single_choice',
  'options': [{'label': 'A', 'content': 'Namenode Federation'},
              {'label': 'B', 'content': 'HA'},
              {'label': 'C', 'content': 'HDFS'},
              {'label': 'D', 'content': 'Yarn'}],
  'student_answer': 'D',
  'correct_answer': 'D',
  'student_answer_display': 'D',
  'correct_answer_display': 'D',
  'is_correct': True,
  'analysis': '',
  'knowledge_point_names': [],
  'difficulty': 'easy',
  'score': 2.0},
 {'order': 7,
  'content': '在Hadoop项目结构中，HDFS指的是什么?( )',
  'question_type': 'single_choice',
  'options': [{'label': 'A', 'content': '分布式文件系统'},
              {'label': 'B', 'content': '分布式并行编程模型'},
              {'label': 'C', 'content': '资源管理和调度器'},
              {'label': 'D', 'content': 'Hadoop上的数据仓库'}],
  'student_answer': 'B',
  'correct_answer': 'A',
  'student_answer_display': 'B',
  'correct_answer_display': 'A',
  'is_correct': False,
  'analysis': '',
  'knowledge_point_names': [],
  'difficulty': 'easy',
  'score': 2.0},
 {'order': 8,
  'content': 'Hadoop的两大核心是（ ）和（ ）',
  'question_type': 'single_choice',
  'options': [{'label': 'A', 'content': 'GFS; MapReduce'},
              {'label': 'B', 'content': 'HDFS; HBase'},
              {'label': 'C', 'content': 'HDFS; MapReduce'},
              {'label': 'D', 'content': 'MapReduce; HBase'}],
  'student_answer': 'C',
  'correct_answer': 'C',
  'student_answer_display': 'C',
  'correct_answer_display': 'C',
  'is_correct': True,
  'analysis': '',
  'knowledge_point_names': [],
  'difficulty': 'easy',
  'score': 2.0},
 {'order': 9,
  'content': '下面与HDFS类似的框架是（ ）',
  'question_type': 'single_choice',
  'options': [{'label': 'A', 'content': 'NTFS'},
              {'label': 'B', 'content': 'FAT32'},
              {'label': 'C', 'content': 'GFS'},
              {'label': 'D', 'content': 'EXT3'}],
  'student_answer': 'C',
  'correct_answer': 'C',
  'student_answer_display': 'C',
  'correct_answer_display': 'C',
  'is_correct': True,
  'analysis': '',
  'knowledge_point_names': [],
  'difficulty': 'easy',
  'score': 2.0},
 {'order': 10,
  'content': 'HDFS中查看某个目录下文件列表的命令是（ ）。',
  'question_type': 'single_choice',
  'options': [{'label': 'A', 'content': 'hdfs dfs -ls'},
              {'label': 'B', 'content': 'hdfs dfs -view'},
              {'label': 'C', 'content': 'hdfs dfs -list'},
              {'label': 'D', 'content': 'hdfs dfs -show'}],
  'student_answer': 'A',
  'correct_answer': 'A',
  'student_answer_display': 'A',
  'correct_answer_display': 'A',
  'is_correct': True,
  'analysis': '`-ls`是HDFS中列出目录内容的标准命令，可查看文件名、权限、大小等信息。',
  'knowledge_point_names': [],
  'difficulty': 'medium',
  'score': 2.0},
 {'order': 11,
  'content': 'mapreduce是（ ）工具',
  'question_type': 'single_choice',
  'options': [{'label': 'A', 'content': '数据存储'},
              {'label': 'B', 'content': '数据处理'},
              {'label': 'C', 'content': '网络技术'},
              {'label': 'D', 'content': '数据安全'}],
  'student_answer': 'B',
  'correct_answer': 'B',
  'student_answer_display': 'B',
  'correct_answer_display': 'B',
  'is_correct': True,
  'analysis': '',
  'knowledge_point_names': [],
  'difficulty': 'easy',
  'score': 2.0},
 {'order': 12,
  'content': '下列关于Map和Reduce函数的描述，哪个是错误的?( )',
  'question_type': 'single_choice',
  'options': [{'label': 'A', 'content': 'Map将小数据集进一步解析成一批<key,value>对，输入Map函数中进行处理'},
              {'label': 'B', 'content': 'Map每一个输入的<k 1 ,v 1 >会输出一批<k 2 ,v 2 >。<k 2 ,v 2 >是计算的中间结果'},
              {'label': 'C', 'content': 'Reduce输入的中间结果<k 2 ,List(v 2 )>中的List(v 2 )表示是一批属于不同k 2 的value'},
              {'label': 'D', 'content': 'Reduce输入的中间结果<k 2 ,List(v 2 )>中的List(v 2 )表示是一批属于同一个k 2 的value'}],
  'student_answer': 'A',
  'correct_answer': 'C',
  'student_answer_display': 'A',
  'correct_answer_display': 'C',
  'is_correct': False,
  'analysis': '',
  'knowledge_point_names': [],
  'difficulty': 'easy',
  'score': 2.0},
 {'order': 13,
  'content': '对于文本行“hello hadoop hello world”，经过WordCount的Reduce函数处理后的结果是:',
  'question_type': 'single_choice',
  'options': [{'label': 'A', 'content': '<"hello",2><"hadoop",1><"world",1>'},
              {'label': 'B', 'content': '<"hello",<1,1>><"hadoop",1><"world",1>'},
              {'label': 'C', 'content': '<"hello",1,1><"hadoop",1><"world",1>'},
              {'label': 'D', 'content': '<"hello",1><"hello",1><"hadoop",1><"world",1>'}],
  'student_answer': 'A',
  'correct_answer': 'A',
  'student_answer_display': 'A',
  'correct_answer_display': 'A',
  'is_correct': True,
  'analysis': '',
  'knowledge_point_names': [],
  'difficulty': 'easy',
  'score': 2.0},
 {'order': 14,
  'content': '下列关于BigTable的描述，哪个是错误的?( )',
  'question_type': 'single_choice',
  'options': [{'label': 'A', 'content': '爬虫持续不断地抓取新页面，这些页面每隔一段时间地存储到BigTable里'},
              {'label': 'B', 'content': 'BigTable是一个分布式存储系统'},
              {'label': 'C', 'content': 'BigTable起初用于解决典型的互联网搜索问题'},
              {'label': 'D', 'content': '网络搜索应用查询建立好的索引，从BigTable得到网页'}],
  'student_answer': 'A',
  'correct_answer': 'A',
  'student_answer_display': 'A',
  'correct_answer_display': 'A',
  'is_correct': True,
  'analysis': '',
  'knowledge_point_names': [],
  'difficulty': 'easy',
  'score': 2.0},
 {'order': 15,
  'content': '在HBase中，用于创建表的命令是？',
  'question_type': 'single_choice',
  'options': [{'label': 'A', 'content': 'create_table'},
              {'label': 'B', 'content': 'hbase create'},
              {'label': 'C', 'content': "create 'table_name'"},
              {'label': 'D', 'content': "add_table 'table_name'"}],
  'student_answer': 'C',
  'correct_answer': 'C',
  'student_answer_display': 'C',
  'correct_answer_display': 'C',
  'is_correct': True,
  'analysis': "在HBase Shell中，创建表的标准命令是`create 'table_name', 'column_family'`。它通过Shell接口与HBase交互。",
  'knowledge_point_names': [],
  'difficulty': 'medium',
  'score': 2.0},
 {'order': 16,
  'content': '\u200c下列关于Hive的说法正确的是:',
  'question_type': 'single_choice',
  'options': [{'label': 'A', 'content': 'Hive不支持索引'},
              {'label': 'B', 'content': 'Hive的可扩展性差'},
              {'label': 'C', 'content': 'Hive支持频繁数据更新'},
              {'label': 'D', 'content': 'Hive支持批量导入'}],
  'student_answer': 'D',
  'correct_answer': 'D',
  'student_answer_display': 'D',
  'correct_answer_display': 'D',
  'is_correct': True,
  'analysis': '',
  'knowledge_point_names': [],
  'difficulty': 'easy',
  'score': 2.0},
 {'order': 17,
  'content': 'Hive 是基于哪种计算框架开发的大数据处理工具？',
  'question_type': 'single_choice',
  'options': [{'label': 'A', 'content': 'MapReduce'},
              {'label': 'B', 'content': 'Spark'},
              {'label': 'C', 'content': 'Flink'},
              {'label': 'D', 'content': 'Storm'}],
  'student_answer': 'B',
  'correct_answer': 'A',
  'student_answer_display': 'B',
  'correct_answer_display': 'A',
  'is_correct': False,
  'analysis': 'Hive 最初是基于 MapReduce 构建的，用于处理大规模数据集的 SQL 查询工具。',
  'knowledge_point_names': [],
  'difficulty': 'easy',
  'score': 2.0},
 {'order': 18,
  'content': '下列关于Spark的描述，错误的是哪一项?( )',
  'question_type': 'single_choice',
  'options': [{'label': 'A', 'content': 'Spark最初由美国加州伯克利大学(UCBerkeley)的AMP实验室于2009年开发'},
              {'label': 'B', 'content': 'Spark在2014年打破了Hadoop保持的基准排序纪录.'},
              {'label': 'C', 'content': 'Spark用十分之一的计算资源，获得了比Hadoop快3倍的速度'},
              {'label': 'D', 'content': 'Spark运行模式单一'}],
  'student_answer': 'D',
  'correct_answer': 'D',
  'student_answer_display': 'D',
  'correct_answer_display': 'D',
  'is_correct': True,
  'analysis': '',
  'knowledge_point_names': [],
  'difficulty': 'easy',
  'score': 2.0},
 {'order': 19,
  'content': '\u200fRDD操作分为转换（Transformation）和动作（Action）两种类型，下列属于动作（Action）类型的操作的是:',
  'question_type': 'single_choice',
  'options': [{'label': 'A', 'content': 'count'},
              {'label': 'B', 'content': 'filter'},
              {'label': 'C', 'content': 'map'},
              {'label': 'D', 'content': 'groupBy'}],
  'student_answer': 'A',
  'correct_answer': 'A',
  'student_answer_display': 'A',
  'correct_answer_display': 'A',
  'is_correct': True,
  'analysis': '',
  'knowledge_point_names': [],
  'difficulty': 'easy',
  'score': 2.0},
 {'order': 20,
  'content': '下列哪一项是线性回归模型中常用的优化算法？',
  'question_type': 'single_choice',
  'options': [{'label': 'A', 'content': '梯度下降法'},
              {'label': 'B', 'content': 'K-means 聚类'},
              {'label': 'C', 'content': '决策树'},
              {'label': 'D', 'content': '朴素贝叶斯'}],
  'student_answer': 'A',
  'correct_answer': 'A',
  'student_answer_display': 'A',
  'correct_answer_display': 'A',
  'is_correct': True,
  'analysis': '梯度下降是一种常用的一阶优化算法，用于最小化线性回归的损失函数。',
  'knowledge_point_names': [],
  'difficulty': 'easy',
  'score': 2.0},
 {'order': 21,
  'content': '在PySpark中，实现线性回归模型时，下列哪个模块是最常用的？',
  'question_type': 'single_choice',
  'options': [{'label': 'A', 'content': 'pyspark.sql.functions'},
              {'label': 'B', 'content': 'pyspark.mllib.regression'},
              {'label': 'C', 'content': 'pyspark.ml.regression'},
              {'label': 'D', 'content': 'pyspark.streaming'}],
  'student_answer': 'C',
  'correct_answer': 'C',
  'student_answer_display': 'C',
  'correct_answer_display': 'C',
  'is_correct': True,
  'analysis': '在PySpark中，`pyspark.ml.regression` 提供了包括线性回归在内的多种回归算法的实现。',
  'knowledge_point_names': [],
  'difficulty': 'easy',
  'score': 2.0},
 {'order': 22,
  'content': '逻辑回归模型中，正则化的主要目的是什么？',
  'question_type': 'single_choice',
  'options': [{'label': 'A', 'content': '增加模型的训练速度'},
              {'label': 'B', 'content': '防止模型过拟合'},
              {'label': 'C', 'content': '提升模型的分类准确率'},
              {'label': 'D', 'content': '提高特征维度'}],
  'student_answer': 'A',
  'correct_answer': 'B',
  'student_answer_display': 'A',
  'correct_answer_display': 'B',
  'is_correct': False,
  'analysis': '逻辑回归中加入L1或L2正则化项，可以限制模型参数的规模，避免模型过度依赖某些特征，从而减少过拟合风险。',
  'knowledge_point_names': [],
  'difficulty': 'easy',
  'score': 2.0},
 {'order': 23,
  'content': '以下关于聚类的说法中，正确的是？',
  'question_type': 'single_choice',
  'options': [{'label': 'A', 'content': '聚类是一种监督学习方法'},
              {'label': 'B', 'content': '聚类不需要先验知识'},
              {'label': 'C', 'content': '聚类一定能够找到最优解'},
              {'label': 'D', 'content': '聚类只能在二维空间中进行'}],
  'student_answer': 'B',
  'correct_answer': 'B',
  'student_answer_display': 'B',
  'correct_answer_display': 'B',
  'is_correct': True,
  'analysis': '聚类是一种无监督学习方法，通常不需要先验知识来指导聚类过程。',
  'knowledge_point_names': [],
  'difficulty': 'easy',
  'score': 2.0},
 {'order': 24,
  'content': '在PySpark中，推荐数据通常以哪种形式表示？',
  'question_type': 'single_choice',
  'options': [{'label': 'A', 'content': '用户ID, 物品ID, 评分'},
              {'label': 'B', 'content': '物品ID, 时间戳'},
              {'label': 'C', 'content': '用户ID, 物品ID'},
              {'label': 'D', 'content': '物品ID, 分类标签'}],
  'student_answer': 'A',
  'correct_answer': 'A',
  'student_answer_display': 'A',
  'correct_answer_display': 'A',
  'is_correct': True,
  'analysis': '在基于潜在因子的推荐模型中，用户-物品-评分三元组是基本的数据结构，用于训练模型。',
  'knowledge_point_names': [],
  'difficulty': 'medium',
  'score': 2.0},
 {'order': 25,
  'content': '在 PySpark 中，下列哪一项常用于去除停用词（stop words）？',
  'question_type': 'single_choice',
  'options': [{'label': 'A', 'content': 'StopWordsRemover()'},
              {'label': 'B', 'content': 'HashingTF()'},
              {'label': 'C', 'content': 'Word2Vec()'},
              {'label': 'D', 'content': 'NGram()'}],
  'student_answer': 'A',
  'correct_answer': 'A',
  'student_answer_display': 'A',
  'correct_answer_display': 'A',
  'is_correct': True,
  'analysis': 'PySpark 提供了 `StopWordsRemover` 类，专门用于移除文本中的停用词，因此它是正确答案。',
  'knowledge_point_names': [],
  'difficulty': 'easy',
  'score': 2.0},
 {'order': 26,
  'content': '在大数据的计算模式中，流计算解决的是什么问题?( )',
  'question_type': 'single_choice',
  'options': [{'label': 'A', 'content': '针对大规模数据的批量处理'},
              {'label': 'B', 'content': '针对大规模图结构数据的处理'},
              {'label': 'C', 'content': '大规模数据的存储管理和查询分析'},
              {'label': 'D', 'content': '针对流数据的实时计算'}],
  'student_answer': 'D',
  'correct_answer': 'D',
  'student_answer_display': 'D',
  'correct_answer_display': 'D',
  'is_correct': True,
  'analysis': '',
  'knowledge_point_names': [],
  'difficulty': 'easy',
  'score': 2.0},
 {'order': 27,
  'content': '下面关于云计算数据中心的描述正确的是:( )',
  'question_type': 'single_choice',
  'options': [{'label': 'A', 'content': '数据中心是云计算的重要载体，为各种平台和应用提供运行支撑环境'},
              {'label': 'B', 'content': '数据中心就是放在企业内部的一台中心服务器'},
              {'label': 'C', 'content': '每个企业都需要建设一个云计算数据中心'},
              {'label': 'D', 'content': '数据中心不需要网络带宽的支撑'}],
  'student_answer': 'B',
  'correct_answer': 'A',
  'student_answer_display': 'B',
  'correct_answer_display': 'A',
  'is_correct': False,
  'analysis': '',
  'knowledge_point_names': [],
  'difficulty': 'easy',
  'score': 2.0},
 {'order': 28,
  'content': "在大数据领域，'Value'主要指的是什么？",
  'question_type': 'single_choice',
  'options': [{'label': 'A', 'content': '数据的总量'},
              {'label': 'B', 'content': '数据的处理速度'},
              {'label': 'C', 'content': '数据的潜在商业价值'},
              {'label': 'D', 'content': '数据的格式种类'}],
  'student_answer': 'C',
  'correct_answer': 'C',
  'student_answer_display': 'C',
  'correct_answer_display': 'C',
  'is_correct': True,
  'analysis': "'Value'强调大数据中隐藏的信息和可提取的商业价值。",
  'knowledge_point_names': [],
  'difficulty': 'medium',
  'score': 2.0},
 {'order': 29,
  'content': '下列哪个不属于Hadoop的特性?( )',
  'question_type': 'single_choice',
  'options': [{'label': 'A', 'content': '成本高'},
              {'label': 'B', 'content': '高可靠性'},
              {'label': 'C', 'content': '高容错性'},
              {'label': 'D', 'content': '运行在Linux平台上'}],
  'student_answer': 'A',
  'correct_answer': 'A',
  'student_answer_display': 'A',
  'correct_answer_display': 'A',
  'is_correct': True,
  'analysis': '',
  'knowledge_point_names': [],
  'difficulty': 'easy',
  'score': 2.0},
 {'order': 30,
  'content': '下面哪一项不是Hadoop的特性?( )',
  'question_type': 'single_choice',
  'options': [{'label': 'A', 'content': '可扩展性高'},
              {'label': 'B', 'content': '只支持少数几种编程语言'},
              {'label': 'C', 'content': '成本低'},
              {'label': 'D', 'content': '能在linux上运行'}],
  'student_answer': 'B',
  'correct_answer': 'B',
  'student_answer_display': 'B',
  'correct_answer_display': 'B',
  'is_correct': True,
  'analysis': '',
  'knowledge_point_names': [],
  'difficulty': 'easy',
  'score': 2.0},
 {'order': 31,
  'content': '大数据分析可以完全替代人类的决策过程。',
  'question_type': 'true_false',
  'options': [{'label': 'A', 'content': '正确', 'value': 'true'}, {'label': 'B', 'content': '错误', 'value': 'false'}],
  'student_answer': 'false',
  'correct_answer': 'false',
  'student_answer_display': 'false',
  'correct_answer_display': '错误',
  'is_correct': True,
  'analysis': '虽然大数据能提供决策支持，但最终的判断仍需依赖人类经验和伦理考量。',
  'knowledge_point_names': [],
  'difficulty': 'medium',
  'score': 2.0},
 {'order': 32,
  'content': 'Hadoop 支持数据的随机读写',
  'question_type': 'true_false',
  'options': [{'label': 'A', 'content': '正确', 'value': 'true'}, {'label': 'B', 'content': '错误', 'value': 'false'}],
  'student_answer': 'true',
  'correct_answer': 'false',
  'student_answer_display': 'true',
  'correct_answer_display': '错误',
  'is_correct': False,
  'analysis': '',
  'knowledge_point_names': [],
  'difficulty': 'easy',
  'score': 2.0},
 {'order': 33,
  'content': 'Hbase中的数据是按行存储的。',
  'question_type': 'true_false',
  'options': [{'label': 'A', 'content': '正确', 'value': 'true'}, {'label': 'B', 'content': '错误', 'value': 'false'}],
  'student_answer': 'false',
  'correct_answer': 'false',
  'student_answer_display': 'false',
  'correct_answer_display': '错误',
  'is_correct': True,
  'analysis': '',
  'knowledge_point_names': [],
  'difficulty': 'easy',
  'score': 2.0},
 {'order': 34,
  'content': 'Hive 默认使用 HiveQL 作为查询语言，其语法与 SQL 非常相似。',
  'question_type': 'true_false',
  'options': [{'label': 'A', 'content': '正确', 'value': 'true'}, {'label': 'B', 'content': '错误', 'value': 'false'}],
  'student_answer': 'true',
  'correct_answer': 'true',
  'student_answer_display': 'true',
  'correct_answer_display': '正确',
  'is_correct': True,
  'analysis': 'HiveQL 是 Hive 的查询语言，设计上兼容 SQL 的很多语法，使得用户可以快速上手。',
  'knowledge_point_names': [],
  'difficulty': 'easy',
  'score': 2.0},
 {'order': 35,
  'content': 'Spark SQL 仅支持读取数据，无法写入数据。',
  'question_type': 'true_false',
  'options': [{'label': 'A', 'content': '正确', 'value': 'true'}, {'label': 'B', 'content': '错误', 'value': 'false'}],
  'student_answer': 'false',
  'correct_answer': 'false',
  'student_answer_display': 'false',
  'correct_answer_display': '错误',
  'is_correct': True,
  'analysis': 'Spark SQL 提供了 read 和 write 接口，支持对多种数据源的读写操作。',
  'knowledge_point_names': [],
  'difficulty': 'easy',
  'score': 2.0},
 {'order': 36,
  'content': 'DataFrame的distinct()方法可以去除重复的行。',
  'question_type': 'true_false',
  'options': [{'label': 'A', 'content': '正确', 'value': 'true'}, {'label': 'B', 'content': '错误', 'value': 'false'}],
  'student_answer': 'true',
  'correct_answer': 'true',
  'student_answer_display': 'true',
  'correct_answer_display': '正确',
  'is_correct': True,
  'analysis': 'distinct()方法用于去除DataFrame中完全重复的行，保留唯一记录。',
  'knowledge_point_names': [],
  'difficulty': 'easy',
  'score': 2.0},
 {'order': 37,
  'content': '在梯度下降中，学习率越大，越容易快速收敛。',
  'question_type': 'true_false',
  'options': [{'label': 'A', 'content': '正确', 'value': 'true'}, {'label': 'B', 'content': '错误', 'value': 'false'}],
  'student_answer': 'true',
  'correct_answer': 'false',
  'student_answer_display': 'true',
  'correct_answer_display': '错误',
  'is_correct': False,
  'analysis': '学习率太大可能导致震荡甚至发散，而非快速收敛。',
  'knowledge_point_names': [],
  'difficulty': 'easy',
  'score': 2.0},
 {'order': 38,
  'content': '逻辑回归模型主要用于回归分析，不能用做分类模型。',
  'question_type': 'true_false',
  'options': [{'label': 'A', 'content': '正确', 'value': 'true'}, {'label': 'B', 'content': '错误', 'value': 'false'}],
  'student_answer': 'false',
  'correct_answer': 'false',
  'student_answer_display': 'false',
  'correct_answer_display': '错误',
  'is_correct': True,
  'analysis': '',
  'knowledge_point_names': [],
  'difficulty': 'easy',
  'score': 2.0},
 {'order': 39,
  'content': 'AUC值可以衡量分类模型的效果，AUC值越接近1，分类效果越好。',
  'question_type': 'true_false',
  'options': [{'label': 'A', 'content': '正确', 'value': 'true'}, {'label': 'B', 'content': '错误', 'value': 'false'}],
  'student_answer': 'true',
  'correct_answer': 'true',
  'student_answer_display': 'true',
  'correct_answer_display': '正确',
  'is_correct': True,
  'analysis': '',
  'knowledge_point_names': [],
  'difficulty': 'easy',
  'score': 2.0},
 {'order': 40,
  'content': '逻辑回归模型在PySpark中主要用于解决分类问题。',
  'question_type': 'true_false',
  'options': [{'label': 'A', 'content': '正确', 'value': 'true'}, {'label': 'B', 'content': '错误', 'value': 'false'}],
  'student_answer': 'true',
  'correct_answer': 'true',
  'student_answer_display': 'true',
  'correct_answer_display': '正确',
  'is_correct': True,
  'analysis': '逻辑回归是经典的分类算法，PySpark中也广泛用于二分类或多分类任务。',
  'knowledge_point_names': [],
  'difficulty': 'easy',
  'score': 2.0},
 {'order': 41,
  'content': '决策树可作为分类算法，也可用于回归模型。',
  'question_type': 'true_false',
  'options': [{'label': 'A', 'content': '正确', 'value': 'true'}, {'label': 'B', 'content': '错误', 'value': 'false'}],
  'student_answer': 'true',
  'correct_answer': 'true',
  'student_answer_display': 'true',
  'correct_answer_display': '正确',
  'is_correct': True,
  'analysis': '',
  'knowledge_point_names': [],
  'difficulty': 'easy',
  'score': 2.0},
 {'order': 42,
  'content': '随机森林中的每棵决策树在训练时使用的是完整的特征集合。',
  'question_type': 'true_false',
  'options': [{'label': 'A', 'content': '正确', 'value': 'true'}, {'label': 'B', 'content': '错误', 'value': 'false'}],
  'student_answer': 'true',
  'correct_answer': 'false',
  'student_answer_display': 'true',
  'correct_answer_display': '错误',
  'is_correct': False,
  'analysis': '随机森林在每棵树的每个节点划分时，会随机选择一部分特征进行考虑，以增加多样性并降低过拟合风险。',
  'knowledge_point_names': [],
  'difficulty': 'medium',
  'score': 2.0},
 {'order': 43,
  'content': '在PySpark中，随机森林的训练过程是并行执行的。',
  'question_type': 'true_false',
  'options': [{'label': 'A', 'content': '正确', 'value': 'true'}, {'label': 'B', 'content': '错误', 'value': 'false'}],
  'student_answer': 'true',
  'correct_answer': 'true',
  'student_answer_display': 'true',
  'correct_answer_display': '正确',
  'is_correct': True,
  'analysis': 'PySpark基于Spark分布式计算框架，随机森林训练过程中每棵树的构建可以并行执行，显著提高了训练效率。',
  'knowledge_point_names': [],
  'difficulty': 'medium',
  'score': 2.0},
 {'order': 44,
  'content': 'K-means算法在初始化时需要选定K个初始簇中心，这些中心通常是随机选取的。',
  'question_type': 'true_false',
  'options': [{'label': 'A', 'content': '正确', 'value': 'true'}, {'label': 'B', 'content': '错误', 'value': 'false'}],
  'student_answer': 'true',
  'correct_answer': 'true',
  'student_answer_display': 'true',
  'correct_answer_display': '正确',
  'is_correct': True,
  'analysis': 'K-means算法确实通过随机选择K个样本作为初始簇中心来启动迭代过程。',
  'knowledge_point_names': [],
  'difficulty': 'easy',
  'score': 2.0},
 {'order': 45,
  'content': 'K-medoids算法能够处理噪声和异常值的能力较K-means强。',
  'question_type': 'true_false',
  'options': [{'label': 'A', 'content': '正确', 'value': 'true'}, {'label': 'B', 'content': '错误', 'value': 'false'}],
  'student_answer': 'true',
  'correct_answer': 'true',
  'student_answer_display': 'true',
  'correct_answer_display': '正确',
  'is_correct': True,
  'analysis': '由于K-medoids选择实际数据点作为中心，相比K-means的均值中心，它对噪声和异常值更鲁棒。',
  'knowledge_point_names': [],
  'difficulty': 'easy',
  'score': 2.0},
 {'order': 46,
  'content': '轮廓系数越小，表示聚类效果越好。',
  'question_type': 'true_false',
  'options': [{'label': 'A', 'content': '正确', 'value': 'true'}, {'label': 'B', 'content': '错误', 'value': 'false'}],
  'student_answer': 'false',
  'correct_answer': 'false',
  'student_answer_display': 'false',
  'correct_answer_display': '错误',
  'is_correct': True,
  'analysis': '轮廓系数越大，表示样本既紧密地聚集在其自身的簇中，又远离其他簇，聚类效果越好。',
  'knowledge_point_names': [],
  'difficulty': 'easy',
  'score': 2.0},
 {'order': 47,
  'content': '层次聚类方法可以通过绘制树状图（dendrogram）来可视化结果。',
  'question_type': 'true_false',
  'options': [{'label': 'A', 'content': '正确', 'value': 'true'}, {'label': 'B', 'content': '错误', 'value': 'false'}],
  'student_answer': 'false',
  'correct_answer': 'true',
  'student_answer_display': 'false',
  'correct_answer_display': '正确',
  'is_correct': False,
  'analysis': '树状图能够直观地展示层次聚类过程中簇的合并过程及相似度阈值。',
  'knowledge_point_names': [],
  'difficulty': 'easy',
  'score': 2.0},
 {'order': 48,
  'content': '协同过滤是最知名的推荐算法，可分为基于用户的协同过滤和基于物品的协同过滤。',
  'question_type': 'true_false',
  'options': [{'label': 'A', 'content': '正确', 'value': 'true'}, {'label': 'B', 'content': '错误', 'value': 'false'}],
  'student_answer': 'true',
  'correct_answer': 'true',
  'student_answer_display': 'true',
  'correct_answer_display': '正确',
  'is_correct': True,
  'analysis': '',
  'knowledge_point_names': [],
  'difficulty': 'easy',
  'score': 2.0},
 {'order': 49,
  'content': '基于潜在因子的推荐方法能够有效解决评分数据稀疏的问题。',
  'question_type': 'true_false',
  'options': [{'label': 'A', 'content': '正确', 'value': 'true'}, {'label': 'B', 'content': '错误', 'value': 'false'}],
  'student_answer': 'true',
  'correct_answer': 'true',
  'student_answer_display': 'true',
  'correct_answer_display': '正确',
  'is_correct': True,
  'analysis': '潜在因子模型通过嵌入用户和物品到低维隐向量空间，能够在稀疏评分矩阵中找到潜在模式，从而提高推荐效果。',
  'knowledge_point_names': [],
  'difficulty': 'medium',
  'score': 2.0},
 {'order': 50,
  'content': '文本向量表示是将自然语言文本转化为数值向量，以便于计算机进行处理。',
  'question_type': 'true_false',
  'options': [{'label': 'A', 'content': '正确', 'value': 'true'}, {'label': 'B', 'content': '错误', 'value': 'false'}],
  'student_answer': 'true',
  'correct_answer': 'true',
  'student_answer_display': 'true',
  'correct_answer_display': '正确',
  'is_correct': True,
  'analysis': '文本向量表示确实是将非结构化的文本信息转换为可以用于机器学习模型的数学向量形式。',
  'knowledge_point_names': [],
  'difficulty': 'easy',
  'score': 2.0}]


INLINE_QUESTION_KNOWLEDGE_POINTS = {
    1: ["大数据基本概念"],
    2: ["大数据基本概念"],
    3: ["大数据关键技术"],
    4: ["大数据应用"],
    5: ["Hadoop"],
    6: ["Hadoop项目结构", "Hadoop发展与演变"],
    7: ["Hadoop项目结构", "HDFS"],
    8: ["HDFS", "MapReduce"],
    9: ["HDFS工作原理"],
    10: ["HDFS基本操作"],
    11: ["MapReduce"],
    12: ["MapReduce工作原理"],
    13: ["MapReduce工作原理"],
    14: ["NoSql数据库"],
    15: ["NoSql数据库"],
    16: ["Hive"],
    17: ["MapReduce"],
    18: ["Spark"],
    19: ["Spark工作原理"],
    20: ["梯度下降"],
    21: ["PySpark线性回归应用"],
    22: ["模型优化方法"],
    23: ["聚类"],
    24: ["基于潜在因子的推荐方法"],
    25: ["PySpark文本处理应用"],
    26: ["大数据关键技术"],
    27: ["云数据库"],
    28: ["大数据基本概念"],
    29: ["Hadoop"],
    30: ["Hadoop"],
    31: ["大数据应用"],
    32: ["Hadoop"],
    33: ["NoSql数据库"],
    34: ["Hive基本操作"],
    35: ["Spark SQL原理与特征"],
    36: ["Spark SQL基本操作"],
    37: ["梯度下降"],
    38: ["罗辑回归模型原理"],
    39: ["模型评价指标"],
    40: ["PySpark罗辑回归应用"],
    41: ["决策树算法原理"],
    42: ["随机森林方法原理"],
    43: ["PySpark随机森林应用"],
    44: ["kmeans算法原理"],
    45: ["k-medoids算法原理"],
    46: ["聚类"],
    47: ["层次聚类方法原理"],
    48: ["推荐系统"],
    49: ["基于潜在因子的推荐方法"],
    50: ["文本向量表示"],
}


INLINE_REPORT_MASTERY = {'大数据概述': 0.5,
 'Hadoop 生态': 0.55,
 'Spark 基础': 0.6,
 'Spark定义与特征': 0.87,
 '大数据存储与管理': 0.98,
 'Spark SQL原理与特征': 0.24,
 '大数据技术基础': 0.85,
 '大数据基本概念': 0.33,
 '大数据关键技术': 0.33,
 '大数据应用': 0.54,
 'Hadoop': 0.68,
 'Hadoop定义与特征': 0.47,
 'Hadoop发展与演变': 0.58,
 'Hadoop项目结构': 0.52,
 'HDFS': 0.69,
 'HDFS定义与特征': 0.73,
 'HDFS工作原理': 0.58,
 'HDFS基本操作': 0.65,
 'MapReduce': 0.59,
 'MapReduce定义与特征': 0.54,
 'MapReduce工作原理': 0.6,
 'MapReduce应用': 0.6,
 'Hive': 0.42,
 'Hive定义与特征': 0.64,
 'Hive工作原理': 0.64,
 'Hive基本操作': 0.53,
 'Spark': 0.66,
 'Spark工作原理': 0.57,
 'Spark SQL基本操作': 0.47,
 '大数据智能分析挖掘': 0.87,
 '线性回归': 0.78,
 '线性回归模型原理': 0.58,
 '梯度下降': 0.53,
 'PySpark线性回归应用': 0.51,
 '逻辑回归': 0.33,
 '罗辑回归模型原理': 0.62,
 '模型评价指标': 0.62,
 '模型优化方法': 0.64,
 'PySpark罗辑回归应用': 0.67,
 '决策树': 0.48,
 '决策树核心概念': 0.33,
 '决策树算法原理': 0.63,
 '随机森林方法原理': 0.43,
 'PySpark随机森林应用': 0.54,
 '聚类': 0.57,
 'kmeans算法原理': 0.69,
 'k-medoids算法原理': 0.59,
 '层次聚类方法原理': 0.59,
 'PySpark聚类应用': 0.4,
 '推荐系统': 0.71,
 '推荐方法分类和原理': 0.5,
 '基于潜在因子的推荐方法': 0.97,
 'PySpark推荐应用': 0.73,
 '自然预测处理基础': 0.62,
 '文本向量表示': 0.75,
 'PySpark文本处理应用': 0.43,
 '大数据领域热点研究': 0.7,
 'NoSql数据库': 0.5,
 '云数据库': 0.48,
 'Hadoop安装与使用': 0.42,
 'Hive安装与使用': 0.63,
 'Spark安装与使用': 0.37,
 '大数据智能应用实践': 0.76,
 'PySpark线性回归实践': 0.48,
 'PySpark逻辑回归实践': 0.33,
 'PySpark随机森林实践': 0.41,
 'PySpark聚类实践': 0.65,
 'PySpark推荐实践': 0.67,
 'PySpark自然语言处理实践': 0.31,
 '综合实践': 0.29,
 '大数据概念与特征': 0.78,
 'Hadoop 生态组成': 0.81,
 'Spark 核心计算模型': 0.61,
 '大数据系统实践': 0.24}


INLINE_FEEDBACK_REPORT = {'summary': '当前画像基于课程资源示例中的 50 道初始评测题生成，系统已识别出薄弱知识点，但仍需要通过后续学习行为逐步校准掌握度。',
 'knowledge_gaps': ['大数据技术基础', '大数据概述', '大数据基本概念'],
 'recommendations': ['优先学习路径中的首个激活节点，巩固最基础的核心概念。', '先补足 25% 基线知识点对应的课程资源，再进入后续练习。'],
 'next_tasks': ['完成当前激活的首个学习节点。', '学习后重新查看画像与掌握度变化。'],
 'encouragement': '当前结果适合作为“刚完成初始评测”的真实起点数据，不代表稳定掌握水平。',
 'conclusion': '当前结果适合作为“刚完成初始评测”的真实起点数据，不代表稳定掌握水平。'}


INLINE_PROFILE = {'summary': '你在大数据存储与管理（98%）、基于潜在因子的推荐方法（97%）等优势领域表现突出，但整体掌握仅57.3%，43个知识点薄弱，尤其综合实践（24%）、Spark '
            'SQL原理（24%）、自然语言处理实践（31%）亟待加强。你偏好晚间视频学习，具备视觉型学习风格和挑战意愿，建议利用这一特点攻坚薄弱环节。',
 'weakness': '综合实践（程序性，掌握率24%）：大数据项目的完整流程整合能力严重不足、Spark SQL原理与特征（概念性，24%）：对Spark '
             'SQL核心机制理解薄弱、PySpark自然语言处理实践（程序性，31%）：文本处理实际应用经验欠缺',
 'suggestion': '建议利用晚间（你偏好的学习时段）进行针对性强化，分三阶段：首先花3天观看Spark '
               'SQL原理系列视频（如B站或官方教程），配合可视化思维导图梳理概念，每天45分钟。接着花2天学习自然语言处理实践，从PySpark文本预处理开始，完成3个简单任务（分词、词频统计、情感分析），使用Jupyter '
               "Notebook边敲代码边记录。最后用2天做综合实践，选择Kaggle上的电商大数据分析项目，从数据清洗到建模全面练习，主动接受挑战以激发动力。每周复习（你偏好每周一次）时用测试题检验掌握率，重点追击低于60%的知识点。资源推荐：'大数据技术实战'视频课（晚间学习）和《Spark快速大数据分析》电子书，配合你喜欢的视觉化笔记工具。"}


INLINE_PATH_NODE_PAYLOADS = [{'order': 0,
  'title': '大数据概念基础复盘',
  'node_type': 'study',
  'status': 'completed',
  'estimated_minutes': 45,
  'goal': '掌握大数据概念基础复盘的核心概念及应用。',
  'criterion': '完成推荐资源学习并能回答核心概念问题。',
  'suggestion': '结合课程资源复习大数据概念基础复盘相关内容。',
  'knowledge_point_name': '大数据概述',
  'mastery_before': 0.25,
  'mastery_after': 0.5},
 {'order': 1,
  'title': 'Spark定义与特征巩固',
  'node_type': 'study',
  'status': 'completed',
  'estimated_minutes': 45,
  'goal': '掌握Spark定义与特征的核心概念及应用。',
  'criterion': '完成推荐资源学习并能回答核心概念问题。',
  'suggestion': '结合课程资源复习Spark定义与特征相关内容。',
  'knowledge_point_name': 'Spark定义与特征',
  'mastery_before': 0.6,
  'mastery_after': 0.87},
 {'order': 2,
  'title': '大数据智能分析挖掘巩固',
  'node_type': 'study',
  'status': 'completed',
  'estimated_minutes': 45,
  'goal': '掌握大数据智能分析挖掘的核心概念及应用。',
  'criterion': '完成推荐资源学习并能回答核心概念问题。',
  'suggestion': '结合课程资源复习大数据智能分析挖掘相关内容。',
  'knowledge_point_name': '大数据智能分析挖掘',
  'mastery_before': 0.52,
  'mastery_after': 0.87},
 {'order': 3,
  'title': '基于潜在因子的推荐方法巩固',
  'node_type': 'study',
  'status': 'completed',
  'estimated_minutes': 45,
  'goal': '掌握基于潜在因子的推荐方法的核心概念及应用。',
  'criterion': '完成推荐资源学习并能回答核心概念问题。',
  'suggestion': '结合课程资源复习基于潜在因子的推荐方法相关内容。',
  'knowledge_point_name': '基于潜在因子的推荐方法',
  'mastery_before': 0.71,
  'mastery_after': 0.97},
 {'order': 4,
  'title': '大数据存储与管理巩固',
  'node_type': 'study',
  'status': 'completed',
  'estimated_minutes': 45,
  'goal': '掌握大数据存储与管理的核心概念及应用。',
  'criterion': '完成推荐资源学习并能回答核心概念问题。',
  'suggestion': '结合课程资源复习大数据存储与管理相关内容。',
  'knowledge_point_name': '大数据存储与管理',
  'mastery_before': 0.72,
  'mastery_after': 0.98},
 {'order': 5,
  'title': 'Spark SQL原理与特征基础',
  'node_type': 'study',
  'status': 'completed',
  'estimated_minutes': 52,
  'goal': '掌握Spark SQL原理与特征的核心概念及应用',
  'criterion': '完成推荐资源学习并能回答核心概念问题。',
  'suggestion': '重点学习Spark SQL原理与特征相关内容。',
  'knowledge_point_name': 'Spark SQL原理与特征',
  'mastery_before': 0.24,
  'mastery_after': 0.61},
 {'order': 6,
  'title': '大数据系统实践基础',
  'node_type': 'study',
  'status': 'completed',
  'estimated_minutes': 45,
  'goal': '掌握大数据系统实践的核心概念及应用。',
  'criterion': '完成推荐资源学习并能回答核心概念问题。',
  'suggestion': '结合课程资源复习大数据系统实践相关内容。',
  'knowledge_point_name': '大数据系统实践',
  'mastery_before': 0.24,
  'mastery_after': 0.54},
 {'order': 7,
  'title': '综合实践基础',
  'node_type': 'study',
  'status': 'completed',
  'estimated_minutes': 45,
  'goal': '掌握综合实践的核心概念及应用。',
  'criterion': '完成推荐资源学习并能回答核心概念问题。',
  'suggestion': '结合课程资源复习综合实践相关内容。',
  'knowledge_point_name': '综合实践',
  'mastery_before': 0.29,
  'mastery_after': 0.57},
 {'order': 8,
  'title': '阶段测试：Spark SQL原理与特征、大数据系统实践、综合实践',
  'node_type': 'test',
  'status': 'active',
  'estimated_minutes': 45,
  'goal': '检验 Spark SQL、大数据系统实践与综合实践的阶段掌握情况。',
  'criterion': '阶段测试达到 60 分以上后进入后续学习。',
  'suggestion': '完成阶段测试，重点检验 Spark SQL 原理、系统实践与综合实践的薄弱环节。',
  'knowledge_point_name': 'Spark SQL原理与特征',
  'mastery_before': None,
  'mastery_after': None}]


def question_payload_with_points(payload: dict[str, object]) -> dict[str, object]:
    """
    为题目快照补入内置知识点绑定。
    :param payload: 单题原始快照字典。
    :return: 带知识点名称列表的题目快照字典。
    """
    enriched_payload = dict(payload)
    order = int(enriched_payload["order"])
    enriched_payload["knowledge_point_names"] = list(
        INLINE_QUESTION_KNOWLEDGE_POINTS.get(
            order,
            enriched_payload.get("knowledge_point_names") or [],
        )
    )
    return enriched_payload


def load_inline_snapshot() -> DesktopSnapshot:
    """
    返回内置的 student1 大数据课程业务快照。
    :return: 归一化快照。
    """
    return DesktopSnapshot(
        score=80.0,
        correct_count=40,
        total_count=50,
        question_details=[
            QuestionSnapshot(**question_payload_with_points(payload))
            for payload in INLINE_QUESTION_PAYLOADS
        ],
        report_mastery=dict(INLINE_REPORT_MASTERY),
        feedback_report=FeedbackReportSnapshot(**INLINE_FEEDBACK_REPORT),
        profile_summary=str(INLINE_PROFILE["summary"]),
        profile_weakness=str(INLINE_PROFILE["weakness"]),
        profile_suggestion=str(INLINE_PROFILE["suggestion"]),
        ability_scores={"处理速度": 60, "工作记忆": 60, "知觉推理": 60, "言语理解": 60},
        learner_tags=["高效型学习者", "视觉型", "晚间学习", "自适应"],
        path_reason="基于当前画像，已完成基础复盘和薄弱项补强，下一步建议通过阶段测试检验 Spark SQL、大数据系统实践与综合实践掌握情况。",
        path_nodes=[
            PathNodeSnapshot(**payload)
            for payload in INLINE_PATH_NODE_PAYLOADS
        ],
        preset_version=PRESET_VERSION,
    )
