"""学习能力评测的内置默认题目。"""

from __future__ import annotations


DEFAULT_ABILITY_QUESTIONS: tuple[dict[str, object], ...] = (
    {
        "text": "阅读一段复杂的技术文档后，你能在多大程度上用自己的话向他人解释其核心思想？",
        "question_type": "single_select",
        "survey_type": "ability",
        "dimension": "言语理解",
        "options": [
            {"value": "A", "label": "能完整且清晰地复述和解释", "score": 5},
            {"value": "B", "label": "能解释大部分要点", "score": 4},
            {"value": "C", "label": "只能解释部分关键概念", "score": 3},
            {"value": "D", "label": "需要反复阅读才能部分理解", "score": 2},
            {"value": "E", "label": "很难向他人解释", "score": 1},
        ],
        "order": 1,
        "is_global": True,
    },
    {
        "text": "当老师讲解一个有多种含义的术语时，你能区分它在不同语境下的含义吗？",
        "question_type": "single_select",
        "survey_type": "ability",
        "dimension": "言语理解",
        "options": [
            {"value": "A", "label": "几乎总能准确区分", "score": 5},
            {"value": "B", "label": "大多数时候可以", "score": 4},
            {"value": "C", "label": "有时候会混淆", "score": 3},
            {"value": "D", "label": "经常需要查阅资料", "score": 2},
            {"value": "E", "label": "很难区分不同含义", "score": 1},
        ],
        "order": 2,
        "is_global": True,
    },
    {
        "text": "遇到不熟悉的专业词汇，你是否能通过上下文推断其大致含义？",
        "question_type": "single_select",
        "survey_type": "ability",
        "dimension": "言语理解",
        "options": [
            {"value": "A", "label": "几乎总能成功推断", "score": 5},
            {"value": "B", "label": "大多数时候可以", "score": 4},
            {"value": "C", "label": "有时候能推断出来", "score": 3},
            {"value": "D", "label": "很少能推断出来", "score": 2},
            {"value": "E", "label": "完全无法推断", "score": 1},
        ],
        "order": 3,
        "is_global": True,
    },
    {
        "text": "在课堂讨论中，你能多好地组织语言来表达自己的观点和论据？",
        "question_type": "single_select",
        "survey_type": "ability",
        "dimension": "言语理解",
        "options": [
            {"value": "A", "label": "逻辑清晰、论据充分", "score": 5},
            {"value": "B", "label": "能较好地表达主要观点", "score": 4},
            {"value": "C", "label": "有想法但表达不够完整", "score": 3},
            {"value": "D", "label": "较难组织语言来表达", "score": 2},
            {"value": "E", "label": "基本无法参与讨论", "score": 1},
        ],
        "order": 4,
        "is_global": True,
    },
    {
        "text": "观察一组图形或数据的规律（如：2, 6, 12, 20, 30），你能多快发现其中的模式？",
        "question_type": "single_select",
        "survey_type": "ability",
        "dimension": "知觉推理",
        "options": [
            {"value": "A", "label": "几乎立刻就能发现", "score": 5},
            {"value": "B", "label": "需要简短思考后能发现", "score": 4},
            {"value": "C", "label": "需要较长时间分析", "score": 3},
            {"value": "D", "label": "需要提示才能发现", "score": 2},
            {"value": "E", "label": "很难独自发现规律", "score": 1},
        ],
        "order": 5,
        "is_global": True,
    },
    {
        "text": "面对一个复杂问题，你倾向于怎样分析？",
        "question_type": "single_select",
        "survey_type": "ability",
        "dimension": "知觉推理",
        "options": [
            {"value": "A", "label": "将问题拆解为子问题，逐步推理", "score": 5},
            {"value": "B", "label": "画图或列表来帮助分析", "score": 4},
            {"value": "C", "label": "寻找类似案例作参考", "score": 3},
            {"value": "D", "label": "尝试不同方法直到找到答案", "score": 2},
            {"value": "E", "label": "等待老师或他人的指导", "score": 1},
        ],
        "order": 6,
        "is_global": True,
    },
    {
        "text": "当你看到一个流程图或系统架构图时，你能多好地理解各部分之间的关系？",
        "question_type": "single_select",
        "survey_type": "ability",
        "dimension": "知觉推理",
        "options": [
            {"value": "A", "label": "能快速理解整体结构和关系", "score": 5},
            {"value": "B", "label": "能理解大部分关系", "score": 4},
            {"value": "C", "label": "需要一些时间才能理解", "score": 3},
            {"value": "D", "label": "需要文字说明辅助才能理解", "score": 2},
            {"value": "E", "label": "看图形很难理解", "score": 1},
        ],
        "order": 7,
        "is_global": True,
    },
    {
        "text": "你是否擅长在脑中想象和操作空间关系（如想象一个物体旋转后的样子）？",
        "question_type": "single_select",
        "survey_type": "ability",
        "dimension": "知觉推理",
        "options": [
            {"value": "A", "label": "非常擅长，能清晰想象", "score": 5},
            {"value": "B", "label": "大多数情况下可以", "score": 4},
            {"value": "C", "label": "简单的可以，复杂的有困难", "score": 3},
            {"value": "D", "label": "较难在脑中想象", "score": 2},
            {"value": "E", "label": "几乎无法做到", "score": 1},
        ],
        "order": 8,
        "is_global": True,
    },
    {
        "text": "在课堂上听讲时，你能同时理解内容并记录笔记吗？",
        "question_type": "single_select",
        "survey_type": "ability",
        "dimension": "工作记忆",
        "options": [
            {"value": "A", "label": "可以同时进行且不遗漏", "score": 5},
            {"value": "B", "label": "大多数时候可以兼顾", "score": 4},
            {"value": "C", "label": "有时候会记漏要点", "score": 3},
            {"value": "D", "label": "记笔记时经常跟不上讲课内容", "score": 2},
            {"value": "E", "label": "很难同时做两件事", "score": 1},
        ],
        "order": 9,
        "is_global": True,
    },
    {
        "text": "当你在解题过程中需要同时记住多个条件和中间结果时，你的表现如何？",
        "question_type": "single_select",
        "survey_type": "ability",
        "dimension": "工作记忆",
        "options": [
            {"value": "A", "label": "能轻松保持跟踪所有信息", "score": 5},
            {"value": "B", "label": "能记住大部分关键信息", "score": 4},
            {"value": "C", "label": "需要写下来才能管理", "score": 3},
            {"value": "D", "label": "经常忘记中间步骤", "score": 2},
            {"value": "E", "label": "很容易混淆或遗忘", "score": 1},
        ],
        "order": 10,
        "is_global": True,
    },
    {
        "text": "你阅读完一篇长文章后，能记住多少内容？",
        "question_type": "single_select",
        "survey_type": "ability",
        "dimension": "工作记忆",
        "options": [
            {"value": "A", "label": "能记住大部分要点和关键细节", "score": 5},
            {"value": "B", "label": "能记住主要框架和核心要点", "score": 4},
            {"value": "C", "label": "只能记住几个主要概念", "score": 3},
            {"value": "D", "label": "只记得大概印象", "score": 2},
            {"value": "E", "label": "读完很快就忘了", "score": 1},
        ],
        "order": 11,
        "is_global": True,
    },
    {
        "text": "你能在多大程度上在心算中完成多步骤运算（如连续加减乘除）？",
        "question_type": "single_select",
        "survey_type": "ability",
        "dimension": "工作记忆",
        "options": [
            {"value": "A", "label": "能轻松完成复杂心算", "score": 5},
            {"value": "B", "label": "能完成中等难度心算", "score": 4},
            {"value": "C", "label": "只能做简单心算", "score": 3},
            {"value": "D", "label": "需要纸笔辅助", "score": 2},
            {"value": "E", "label": "几乎无法心算", "score": 1},
        ],
        "order": 12,
        "is_global": True,
    },
    {
        "text": "你完成一组简单但数量多的任务（如批量整理文件、重复性练习）的速度如何？",
        "question_type": "single_select",
        "survey_type": "ability",
        "dimension": "处理速度",
        "options": [
            {"value": "A", "label": "非常快且很少出错", "score": 5},
            {"value": "B", "label": "速度较快，偶尔有小错", "score": 4},
            {"value": "C", "label": "速度一般", "score": 3},
            {"value": "D", "label": "速度较慢但准确", "score": 2},
            {"value": "E", "label": "速度慢且容易出错", "score": 1},
        ],
        "order": 13,
        "is_global": True,
    },
    {
        "text": "当你需要集中注意力快速浏览和提取关键信息时，你的效率如何？",
        "question_type": "single_select",
        "survey_type": "ability",
        "dimension": "处理速度",
        "options": [
            {"value": "A", "label": "很快就能找到关键信息", "score": 5},
            {"value": "B", "label": "能较快地定位重点", "score": 4},
            {"value": "C", "label": "需要仔细逐行阅读", "score": 3},
            {"value": "D", "label": "经常漏看关键信息", "score": 2},
            {"value": "E", "label": "无法快速浏览，必须逐字阅读", "score": 1},
        ],
        "order": 14,
        "is_global": True,
    },
    {
        "text": "面对一道你熟悉类型的题目，你通常能多快给出答案？",
        "question_type": "single_select",
        "survey_type": "ability",
        "dimension": "处理速度",
        "options": [
            {"value": "A", "label": "几秒内就能反应", "score": 5},
            {"value": "B", "label": "很快就能回忆起解法", "score": 4},
            {"value": "C", "label": "需要一些时间回忆", "score": 3},
            {"value": "D", "label": "需要较长时间思考", "score": 2},
            {"value": "E", "label": "即使熟悉也很慢", "score": 1},
        ],
        "order": 15,
        "is_global": True,
    },
    {
        "text": "你在限时考试中的时间管理能力如何？",
        "question_type": "single_select",
        "survey_type": "ability",
        "dimension": "处理速度",
        "options": [
            {"value": "A", "label": "总能提前完成且有检查时间", "score": 5},
            {"value": "B", "label": "通常能按时完成", "score": 4},
            {"value": "C", "label": "刚好能完成或略有不足", "score": 3},
            {"value": "D", "label": "经常来不及做完", "score": 2},
            {"value": "E", "label": "总是有大量题目做不完", "score": 1},
        ],
        "order": 16,
        "is_global": True,
    },
)
