# Generated by Django 6.0.1 on 2026-01-20 02:24

import django.db.models.deletion
from django.db import migrations, models


# 定义数据库迁移操作，Django 将按顺序执行以下变更
class Migration(migrations.Migration):

    # 标记为初始迁移，首次创建该应用的数据库表
    initial = True

    # 声明依赖的先前迁移版本
    dependencies = [
        ('courses', '0001_initial'),
    ]

    # 要执行的数据库操作列表
    operations = [
        # 创建数据表模型
        migrations.CreateModel(
            # 模型名称: NodeProgress
            name='NodeProgress',
            # 字段定义列表
            fields=[
                # id: ID (自增主键)
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # completed_resources: 已完成资源ID列表 (JSON 数据字段)
                ('completed_resources', models.JSONField(default=list, verbose_name='已完成资源ID列表')),
                # completed_exams: 已完成测验ID列表 (JSON 数据字段)
                ('completed_exams', models.JSONField(default=list, verbose_name='已完成测验ID列表')),
                # mastery_before: 学习前掌握度 (精确小数字段)
                ('mastery_before', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, verbose_name='学习前掌握度')),
                # mastery_after: 学习后掌握度 (精确小数字段)
                ('mastery_after', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, verbose_name='学习后掌握度')),
                # updated_at: 更新时间 (日期时间字段)
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            # 模型的 Meta 配置选项
            options={
                'verbose_name': '节点进度',
                'verbose_name_plural': '节点进度',
                'db_table': 'node_progress',
            },
        ),
        # 创建数据表模型
        migrations.CreateModel(
            # 模型名称: PathNode
            name='PathNode',
            # 字段定义列表
            fields=[
                # id: ID (自增主键)
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # title: 节点标题 (字符串字段)
                ('title', models.CharField(max_length=200, verbose_name='节点标题')),
                # goal: 学习目标 (长文本字段)
                ('goal', models.TextField(blank=True, null=True, verbose_name='学习目标')),
                # criterion: 达标条件 (长文本字段)
                ('criterion', models.TextField(blank=True, help_text='完成该节点需要达到的条件', null=True, verbose_name='达标条件')),
                # suggestion: 学习建议 (长文本字段)
                ('suggestion', models.TextField(blank=True, null=True, verbose_name='学习建议')),
                # status: 状态 (字符串字段)
                ('status', models.CharField(choices=[('locked', '未解锁'), ('active', '进行中'), ('completed', '已完成'), ('failed', '未通过')], default='locked', max_length=20, verbose_name='状态')),
                # order_index: 顺序 (整数字段)
                ('order_index', models.IntegerField(default=0, verbose_name='顺序')),
                # is_inserted: 是否动态插入 (布尔字段)
                ('is_inserted', models.BooleanField(default=False, help_text='标记是否为系统动态插入的补充节点', verbose_name='是否动态插入')),
                # created_at: 创建时间 (日期时间字段)
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            # 模型的 Meta 配置选项
            options={
                'verbose_name': '路径节点',
                'verbose_name_plural': '路径节点',
                'db_table': 'path_nodes',
                'ordering': ['order_index'],
            },
        ),
        # 创建数据表模型
        migrations.CreateModel(
            # 模型名称: LearningPath
            name='LearningPath',
            # 字段定义列表
            fields=[
                # id: ID (自增主键)
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # ai_reason: 路径理由 (长文本字段)
                ('ai_reason', models.TextField(blank=True, help_text='AI根据用户画像生成的路径规划说明', null=True, verbose_name='路径理由')),
                # is_dynamic: 是否动态调整过 (布尔字段)
                ('is_dynamic', models.BooleanField(default=False, help_text='标记路径是否经过后续的动态调整', verbose_name='是否动态调整过')),
                # generated_at: 生成时间 (日期时间字段)
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
                # updated_at: 更新时间 (日期时间字段)
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                # course: 课程 (外键关联)
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_paths', to='courses.course', verbose_name='课程')),
            ],
            # 模型的 Meta 配置选项
            options={
                'verbose_name': '学习路径',
                'verbose_name_plural': '学习路径',
                'db_table': 'learning_paths',
            },
        ),
    ]
