# Generated by Django 6.0.1 on 2026-01-20 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


# 定义数据库迁移操作，Django 将按顺序执行以下变更
class Migration(migrations.Migration):

    # 标记为初始迁移，首次创建该应用的数据库表
    initial = True

    # 声明依赖的先前迁移版本
    dependencies = [
        ('exams', '0002_initial'),
        ('knowledge', '0002_initial'),
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # 要执行的数据库操作列表
    operations = [
        # 添加新字段
        migrations.AddField(
            # 目标模型: learningpath
            model_name='learningpath',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_paths', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        # 添加新字段
        migrations.AddField(
            # 目标模型: nodeprogress
            model_name='nodeprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_progress', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        # 添加新字段
        migrations.AddField(
            # 目标模型: pathnode
            model_name='pathnode',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='path_nodes', to='exams.exam', verbose_name='节点测验'),
        ),
        # 添加新字段
        migrations.AddField(
            # 目标模型: pathnode
            model_name='pathnode',
            name='knowledge_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='path_nodes', to='knowledge.knowledgepoint', verbose_name='关联知识点'),
        ),
        # 添加新字段
        migrations.AddField(
            # 目标模型: pathnode
            model_name='pathnode',
            name='path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='learning.learningpath', verbose_name='所属路径'),
        ),
        # 添加新字段
        migrations.AddField(
            # 目标模型: pathnode
            model_name='pathnode',
            name='resources',
            field=models.ManyToManyField(blank=True, related_name='path_nodes', to='knowledge.resource', verbose_name='关联资源'),
        ),
        # 添加新字段
        migrations.AddField(
            # 目标模型: nodeprogress
            model_name='nodeprogress',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='learning.pathnode', verbose_name='节点'),
        ),
        # 修改联合唯一约束
        migrations.AlterUniqueTogether(
            name='learningpath',
            unique_together={('user', 'course')},
        ),
        # 修改联合唯一约束
        migrations.AlterUniqueTogether(
            name='nodeprogress',
            unique_together={('node', 'user')},
        ),
    ]
