# Generated by Django 6.0.2 on 2026-02-18 15:41

from django.db import migrations, models


# 定义数据库迁移操作，Django 将按顺序执行以下变更
class Migration(migrations.Migration):

    # 声明依赖的先前迁移版本
    dependencies = [
        ('learning', '0002_initial'),
    ]

    # 要执行的数据库操作列表
    operations = [
        # 修改字段属性
        migrations.AlterField(
            # 目标模型: pathnode
            model_name='pathnode',
            name='status',
            field=models.CharField(choices=[('locked', '未解锁'), ('active', '进行中'), ('completed', '已完成'), ('failed', '未通过'), ('skipped', '已跳过')], default='locked', max_length=20, verbose_name='状态'),
        ),
    ]
