# Generated by Django 6.0.2 on 2026-02-19 04:27

from django.db import migrations, models


# 定义数据库迁移操作，Django 将按顺序执行以下变更
class Migration(migrations.Migration):

    # 声明依赖的先前迁移版本
    dependencies = [
        ('learning', '0003_add_skipped_status'),
    ]

    # 要执行的数据库操作列表
    operations = [
        # 添加新字段
        migrations.AddField(
            # 目标模型: pathnode
            model_name='pathnode',
            name='estimated_minutes',
            field=models.IntegerField(default=30, help_text='预计完成该节点需要的时间（分钟）', verbose_name='预计时长(分钟)'),
        ),
        # 添加新字段
        migrations.AddField(
            # 目标模型: pathnode
            model_name='pathnode',
            name='node_type',
            field=models.CharField(choices=[('study', '学习节点'), ('test', '测试节点')], default='study', help_text='study=学习节点, test=测试节点', max_length=10, verbose_name='节点类型'),
        ),
    ]
