# Generated by Django 6.0.2 on 2026-03-09 00:00

from django.db import migrations, models


# 定义数据库迁移操作，Django 将按顺序执行以下变更
class Migration(migrations.Migration):

    # 声明依赖的先前迁移版本
    dependencies = [
        ('learning', '0004_pathnode_estimated_minutes_pathnode_node_type'),
    ]

    # 要执行的数据库操作列表
    operations = [
        # 添加新字段
        migrations.AddField(
            # 目标模型: nodeprogress
            model_name='nodeprogress',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, help_text='用于存储阶段测试报告、资源播放进度等附加数据', verbose_name='扩展进度数据'),
        ),
    ]