# Generated by Django 6.0.1 on 2026-01-20 02:24

import django.db.models.deletion
from django.db import migrations, models


# 定义数据库迁移操作，Django 将按顺序执行以下变更
class Migration(migrations.Migration):

    # 标记为初始迁移，首次创建该应用的数据库表
    initial = True

    # 声明依赖的先前迁移版本
    dependencies = [
        ('courses', '0001_initial'),
    ]

    # 要执行的数据库操作列表
    operations = [
        # 创建数据表模型
        migrations.CreateModel(
            # 模型名称: ExamQuestion
            name='ExamQuestion',
            # 字段定义列表
            fields=[
                # id: ID (自增主键)
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # score: 分值 (精确小数字段)
                ('score', models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='分值')),
                # order: 排序 (整数字段)
                ('order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            # 模型的 Meta 配置选项
            options={
                'db_table': 'exam_questions',
                'ordering': ['order'],
            },
        ),
        # 创建数据表模型
        migrations.CreateModel(
            # 模型名称: ExamSubmission
            name='ExamSubmission',
            # 字段定义列表
            fields=[
                # id: ID (自增主键)
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # answers: 答案 (JSON 数据字段)
                ('answers', models.JSONField(default=dict, help_text='格式: {question_id: answer, ...}', verbose_name='答案')),
                # score: 得分 (精确小数字段)
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='得分')),
                # is_passed: 是否通过 (布尔字段)
                ('is_passed', models.BooleanField(blank=True, null=True, verbose_name='是否通过')),
                # graded_at: 评分时间 (日期时间字段)
                ('graded_at', models.DateTimeField(blank=True, null=True, verbose_name='评分时间')),
                # submitted_at: 提交时间 (日期时间字段)
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
            ],
            # 模型的 Meta 配置选项
            options={
                'verbose_name': '考试提交',
                'verbose_name_plural': '考试提交',
                'db_table': 'exam_submissions',
            },
        ),
        # 创建数据表模型
        migrations.CreateModel(
            # 模型名称: FeedbackReport
            name='FeedbackReport',
            # 字段定义列表
            fields=[
                # id: ID (自增主键)
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # status: 状态 (字符串字段)
                ('status', models.CharField(choices=[('pending', '生成中'), ('completed', '已完成'), ('failed', '生成失败')], default='pending', max_length=20, verbose_name='状态')),
                # overview: 概览 (JSON 数据字段)
                ('overview', models.JSONField(default=dict, help_text='成绩概览信息', verbose_name='概览')),
                # analysis: 错因分析 (JSON 数据字段)
                ('analysis', models.JSONField(default=list, help_text='每道错题的分析', verbose_name='错因分析')),
                # recommendations: 建议 (JSON 数据字段)
                ('recommendations', models.JSONField(default=list, verbose_name='建议')),
                # next_tasks: 下一步任务 (JSON 数据字段)
                ('next_tasks', models.JSONField(default=list, verbose_name='下一步任务')),
                # conclusion: 总结 (长文本字段)
                ('conclusion', models.TextField(blank=True, null=True, verbose_name='总结')),
                # generated_at: 生成时间 (日期时间字段)
                ('generated_at', models.DateTimeField(auto_now=True, verbose_name='生成时间')),
            ],
            # 模型的 Meta 配置选项
            options={
                'verbose_name': '反馈报告',
                'verbose_name_plural': '反馈报告',
                'db_table': 'feedback_reports',
            },
        ),
        # 创建数据表模型
        migrations.CreateModel(
            # 模型名称: Exam
            name='Exam',
            # 字段定义列表
            fields=[
                # id: ID (自增主键)
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # title: 考试标题 (字符串字段)
                ('title', models.CharField(max_length=200, verbose_name='考试标题')),
                # description: 考试说明 (长文本字段)
                ('description', models.TextField(blank=True, null=True, verbose_name='考试说明')),
                # exam_type: 考试类型 (字符串字段)
                ('exam_type', models.CharField(choices=[('chapter', '章节测验'), ('midterm', '期中考试'), ('final', '期末考试'), ('practice', '练习'), ('node_test', '节点测验')], default='practice', max_length=20, verbose_name='考试类型')),
                # total_score: 总分 (精确小数字段)
                ('total_score', models.DecimalField(decimal_places=2, default=100, max_digits=5, verbose_name='总分')),
                # pass_score: 及格分 (精确小数字段)
                ('pass_score', models.DecimalField(decimal_places=2, default=60, max_digits=5, verbose_name='及格分')),
                # duration: 考试时长(分钟) (整数字段)
                ('duration', models.IntegerField(blank=True, help_text='不设置表示不限时', null=True, verbose_name='考试时长(分钟)')),
                # start_time: 开始时间 (日期时间字段)
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                # end_time: 结束时间 (日期时间字段)
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                # status: 状态 (字符串字段)
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('closed', '已结束')], default='published', max_length=20, verbose_name='状态')),
                # created_at: 创建时间 (日期时间字段)
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                # updated_at: 更新时间 (日期时间字段)
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                # course: 所属课程 (外键关联)
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='courses.course', verbose_name='所属课程')),
            ],
            # 模型的 Meta 配置选项
            options={
                'verbose_name': '考试',
                'verbose_name_plural': '考试',
                'db_table': 'exams',
                'ordering': ['-created_at'],
            },
        ),
    ]
