# Generated by Django 6.0.1 on 2026-01-20 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


# 定义数据库迁移操作，Django 将按顺序执行以下变更
class Migration(migrations.Migration):

    # 标记为初始迁移，首次创建该应用的数据库表
    initial = True

    # 声明依赖的先前迁移版本
    dependencies = [
        ('assessments', '0003_initial'),
        ('courses', '0002_initial'),
        ('exams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # 要执行的数据库操作列表
    operations = [
        # 添加新字段
        migrations.AddField(
            # 目标模型: exam
            model_name='exam',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exams', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        # 添加新字段
        migrations.AddField(
            # 目标模型: exam
            model_name='exam',
            name='target_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='courses.class', verbose_name='目标班级'),
        ),
        # 添加新字段
        migrations.AddField(
            # 目标模型: examquestion
            model_name='examquestion',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.exam'),
        ),
        # 添加新字段
        migrations.AddField(
            # 目标模型: examquestion
            model_name='examquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.question'),
        ),
        # 添加新字段
        migrations.AddField(
            # 目标模型: exam
            model_name='exam',
            name='questions',
            field=models.ManyToManyField(related_name='exams', through='exams.ExamQuestion', to='assessments.question', verbose_name='题目'),
        ),
        # 添加新字段
        migrations.AddField(
            # 目标模型: examsubmission
            model_name='examsubmission',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='exams.exam', verbose_name='考试'),
        ),
        # 添加新字段
        migrations.AddField(
            # 目标模型: examsubmission
            model_name='examsubmission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_submissions', to=settings.AUTH_USER_MODEL, verbose_name='学生'),
        ),
        # 添加新字段
        migrations.AddField(
            # 目标模型: feedbackreport
            model_name='feedbackreport',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_reports', to='exams.exam', verbose_name='考试'),
        ),
        # 添加新字段
        migrations.AddField(
            # 目标模型: feedbackreport
            model_name='feedbackreport',
            name='exam_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_reports', to='exams.examsubmission', verbose_name='提交记录'),
        ),
        # 添加新字段
        migrations.AddField(
            # 目标模型: feedbackreport
            model_name='feedbackreport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_reports', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        # 修改联合唯一约束
        migrations.AlterUniqueTogether(
            name='examsubmission',
            unique_together={('exam', 'user')},
        ),
        # 修改联合唯一约束
        migrations.AlterUniqueTogether(
            name='feedbackreport',
            unique_together={('user', 'exam')},
        ),
    ]
