# Generated by Django 6.0.2 on 2026-02-19 11:32

import django.db.models.deletion
from django.db import migrations, models


# 定义数据库迁移操作，Django 将按顺序执行以下变更
class Migration(migrations.Migration):

    # 声明依赖的先前迁移版本
    dependencies = [
        ('assessments', '0005_question_chapter_question_suggested_score'),
        ('exams', '0002_initial'),
    ]

    # 要执行的数据库操作列表
    operations = [
        # 修改联合唯一约束
        migrations.AlterUniqueTogether(
            name='feedbackreport',
            unique_together=set(),
        ),
        # 添加新字段
        migrations.AddField(
            # 目标模型: feedbackreport
            model_name='feedbackreport',
            name='assessment_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_reports', to='assessments.assessmentresult', verbose_name='评测结果'),
        ),
        # 添加新字段
        migrations.AddField(
            # 目标模型: feedbackreport
            model_name='feedbackreport',
            name='source',
            field=models.CharField(choices=[('exam', '考试'), ('assessment', '初始评测')], default='exam', max_length=20, verbose_name='来源'),
        ),
        # 修改字段属性
        migrations.AlterField(
            # 目标模型: exam
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('chapter', '章节测验'), ('midterm', '期中考试'), ('final', '期末考试'), ('practice', '练习'), ('node_test', '节点测验'), ('question_set', '套题')], default='practice', max_length=20, verbose_name='考试类型'),
        ),
        # 修改字段属性
        migrations.AlterField(
            # 目标模型: feedbackreport
            model_name='feedbackreport',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_reports', to='exams.exam', verbose_name='考试'),
        ),
    ]
