# Generated by Django 6.0.1 on 2026-01-21 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


# 定义数据库迁移操作，Django 将按顺序执行以下变更
class Migration(migrations.Migration):

    # 标记为初始迁移，首次创建该应用的数据库表
    initial = True

    # 声明依赖的先前迁移版本
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # 要执行的数据库操作列表
    operations = [
        # 创建数据表模型
        migrations.CreateModel(
            # 模型名称: OperationLog
            name='OperationLog',
            # 字段定义列表
            fields=[
                # id: ID (自增主键)
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # action_type: 操作类型 (字符串字段)
                ('action_type', models.CharField(choices=[('create', '创建 Create'), ('update', '更新 Update'), ('delete', '删除 Delete'), ('read', '查询 Read'), ('login', '登录 Login'), ('logout', '登出 Logout'), ('export', '导出 Export'), ('import', '导入 Import'), ('other', '其他 Other')], default='other', max_length=20, verbose_name='操作类型')),
                # module: 操作模块 (字符串字段)
                ('module', models.CharField(choices=[('users', '用户模块 Users'), ('courses', '课程模块 Courses'), ('knowledge', '知识模块 Knowledge'), ('exams', '考试模块 Exams'), ('assessments', '测评模块 Assessments'), ('ai_services', 'AI服务模块 AI Services'), ('system', '系统 System')], default='system', max_length=50, verbose_name='操作模块')),
                # description: 操作描述 (字符串字段)
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='操作描述')),
                # request_path: 请求路径 (字符串字段)
                ('request_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='请求路径')),
                # request_method: 请求方法 (字符串字段)
                ('request_method', models.CharField(blank=True, max_length=10, null=True, verbose_name='请求方法')),
                # request_params: 请求参数 (JSON 数据字段)
                ('request_params', models.JSONField(blank=True, default=dict, verbose_name='请求参数')),
                # response_status: 响应状态码 (整数字段)
                ('response_status', models.IntegerField(blank=True, null=True, verbose_name='响应状态码')),
                # is_success: 是否成功 (布尔字段)
                ('is_success', models.BooleanField(default=True, verbose_name='是否成功')),
                # error_message: 错误信息 (长文本字段)
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                # ip_address: IP地址 (IP 地址字段)
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                # user_agent: 用户代理 (字符串字段)
                ('user_agent', models.CharField(blank=True, max_length=500, null=True, verbose_name='用户代理')),
                # created_at: 操作时间 (日期时间字段)
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                # user: 操作用户 (外键关联)
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作用户')),
            ],
            # 模型的 Meta 配置选项
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'db_table': 'operation_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='operation_l_user_id_0c8567_idx'), models.Index(fields=['action_type', 'created_at'], name='operation_l_action__95992b_idx'), models.Index(fields=['module', 'created_at'], name='operation_l_module_f1a84a_idx')],
            },
        ),
    ]
