# Generated by Django 6.0.2 on 2026-02-18 16:00

from django.db import migrations, models


# 定义数据库迁移操作，Django 将按顺序执行以下变更
class Migration(migrations.Migration):

    # 声明依赖的先前迁移版本
    dependencies = [
        ('logs', '0001_initial'),
    ]

    # 要执行的数据库操作列表
    operations = [
        # 修改字段属性
        migrations.AlterField(
            # 目标模型: operationlog
            model_name='operationlog',
            name='module',
            field=models.CharField(choices=[('users', '用户模块 Users'), ('courses', '课程模块 Courses'), ('knowledge', '知识模块 Knowledge'), ('exams', '考试模块 Exams'), ('assessments', '测评模块 Assessments'), ('learning', '学习模块 Learning'), ('ai_services', 'AI服务模块 AI Services'), ('logs', '日志模块 Logs'), ('system', '系统 System')], default='system', max_length=50, verbose_name='操作模块'),
        ),
    ]
