"""
Django settings for wisdom_edu_api project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import configparser
import json
import os
from datetime import timedelta
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")

CONFIG_INI_PATH = BASE_DIR / "config.ini"
_settings_config = configparser.ConfigParser()
if CONFIG_INI_PATH.exists():
    _settings_config.read(CONFIG_INI_PATH, encoding="utf-8")


def _config_value(section: str, key: str, default: str = "") -> str:
    """从 config.ini 读取字符串配置，为环境变量缺省值提供回退。"""
    try:
        return _settings_config.get(section, key)
    except (configparser.NoSectionError, configparser.NoOptionError):
        return default


def _config_int(section: str, key: str, default: int) -> int:
    """从 config.ini 读取整数配置，为运行时参数提供稳定回退。"""
    raw_value = _config_value(section, key, str(default)).strip()
    if raw_value.isdigit():
        return int(raw_value)
    return default


def _config_bool(section: str, key: str, default: bool) -> bool:
    """从 config.ini 读取布尔配置，兼容常见 true/false 写法。"""
    raw_value = _config_value(section, key, str(default)).strip().lower()
    if raw_value in {"1", "true", "yes", "on"}:
        return True
    if raw_value in {"0", "false", "no", "off"}:
        return False
    return default


def _env_config_bool(env_name: str, section: str, key: str, default: bool) -> bool:
    """读取环境变量优先的布尔配置。"""
    raw_value = os.getenv(env_name, "").strip().lower()
    if raw_value in {"1", "true", "yes", "on"}:
        return True
    if raw_value in {"0", "false", "no", "off"}:
        return False
    return _config_bool(section, key, default)


def _config_json_dict(env_name: str, section: str, key: str) -> dict[str, object]:
    """读取 JSON 字典配置，解析失败时返回空字典避免启动中断。"""
    raw_value = os.getenv(env_name, _config_value(section, key, "{}")).strip()
    if not raw_value:
        return {}
    try:
        parsed = json.loads(raw_value)
    except json.JSONDecodeError:
        return {}
    return parsed if isinstance(parsed, dict) else {}


def _env_csv_list(env_name: str, default: str = "") -> list[str]:
    """按逗号解析环境变量列表，并自动去除空白与空项。"""
    raw_value = os.getenv(env_name, default)
    if not raw_value:
        return []
    return [item.strip() for item in raw_value.split(",") if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "SECRET_KEY", "django-insecure-wul(tlxm%wjk^qz0#o1xlf_94ic9!f(mz$_-f5vn)s#fpnhy#3"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "True").lower() == "true"

ALLOWED_HOSTS = _env_csv_list(
    "ALLOWED_HOSTS",
    "localhost,127.0.0.1,edu.qintsg.xyz,106.14.209.7",
) or ["localhost", "127.0.0.1"]

USE_X_FORWARDED_HOST = os.getenv("USE_X_FORWARDED_HOST", "True").lower() == "true"
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# Application definition

INSTALLED_APPS = [
    "daphne",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party apps / 第三方应用
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
    "django_filters",
    "drf_spectacular",
    "channels",
    # Local apps / 本地应用（使用Django startapp创建）
    "users",  # 用户模块：认证、权限、偏好
    "courses",  # 课程模块：课程、班级、选课
    "knowledge",  # 知识图谱模块：知识点、关系、资源
    "assessments",  # 测评模块：题库、测评、能力评分
    "learning",  # 学习路径模块：路径、节点、进度
    "exams",  # 考试模块：考试、提交、反馈报告
    "ai_services",  # AI服务模块：大模型调用日志
    "logs",  # 操作日志模块：系统操作日志记录
    "common",  # 公共模块：工具函数、权限类
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # 操作日志中间件（记录API操作日志）
    "logs.middleware.OperationLogMiddleware",
]

ROOT_URLCONF = "wisdom_edu_api.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "wisdom_edu_api.wsgi.application"
ASGI_APPLICATION = "wisdom_edu_api.asgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME", "wisdom_edu"),
        "USER": os.getenv("DB_USER", "wisdom"),
        "PASSWORD": os.getenv("DB_PASSWORD", "wisdom123"),
        "HOST": os.getenv("DB_HOST", "127.0.0.1"),
        "PORT": os.getenv("DB_PORT", "5432"),
    }
}

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    }
}

# Neo4j Configuration / Neo4j图数据库配置
# Neo4j用于存储知识图谱，支持高效的图查询
# 如果Neo4j不可用，系统会自动回退到PostgreSQL
NEO4J_BOLT_URL = os.getenv("NEO4J_BOLT_URL", "bolt://localhost:7687")
NEO4J_USERNAME = os.getenv("NEO4J_USERNAME", "neo4j")
NEO4J_PASSWORD = os.getenv("NEO4J_PASSWORD", "password")

# GraphRAG runtime configuration / GraphRAG 运行时配置
GRAPHRAG_EMBEDDER_PROVIDER = os.getenv(
    "GRAPHRAG_EMBEDDER_PROVIDER",
    _config_value("graphrag", "embedder_provider", "hash"),
).strip() or "hash"
GRAPHRAG_SENTENCE_MODEL = os.getenv(
    "GRAPHRAG_SENTENCE_MODEL",
    _config_value(
        "graphrag",
        "sentence_model",
        "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2",
    ),
).strip() or "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
GRAPHRAG_VECTOR_DIMENSION = _config_int(
    "graphrag",
    "vector_dimension",
    256,
)
if os.getenv("GRAPHRAG_VECTOR_DIMENSION", "").strip().isdigit():
    GRAPHRAG_VECTOR_DIMENSION = int(os.getenv("GRAPHRAG_VECTOR_DIMENSION", "256"))
GRAPHRAG_QDRANT_PATH = os.getenv(
    "GRAPHRAG_QDRANT_PATH",
    _config_value("graphrag", "qdrant_path", "runtime_logs/rag/qdrant"),
).strip() or "runtime_logs/rag/qdrant"

# Learning resource MCP configuration / 学习资源 MCP 配置
RESOURCE_MCP_ENABLED = _env_config_bool("RESOURCE_MCP_ENABLED", "resource_mcp", "enabled", True)
RESOURCE_MCP_EXA_ENABLED = _env_config_bool("RESOURCE_MCP_EXA_ENABLED", "resource_mcp", "exa_enabled", True)
RESOURCE_MCP_FIRECRAWL_ENABLED = _env_config_bool(
    "RESOURCE_MCP_FIRECRAWL_ENABLED",
    "resource_mcp",
    "firecrawl_enabled",
    True,
)
RESOURCE_MCP_TIMEOUT_SECONDS = _config_int("resource_mcp", "timeout_seconds", 12)
if os.getenv("RESOURCE_MCP_TIMEOUT_SECONDS", "").strip().isdigit():
    RESOURCE_MCP_TIMEOUT_SECONDS = int(os.getenv("RESOURCE_MCP_TIMEOUT_SECONDS", "12"))
RESOURCE_MCP_FIRECRAWL_LIMIT = _config_int("resource_mcp", "firecrawl_limit", 2)
if os.getenv("RESOURCE_MCP_FIRECRAWL_LIMIT", "").strip().isdigit():
    RESOURCE_MCP_FIRECRAWL_LIMIT = int(os.getenv("RESOURCE_MCP_FIRECRAWL_LIMIT", "2"))
EXA_API_KEY = os.getenv("EXA_API_KEY", "")
EXA_SEARCH_URL = os.getenv("EXA_SEARCH_URL", "https://api.exa.ai/search")
EXA_SEARCH_TYPE = os.getenv("EXA_SEARCH_TYPE", _config_value("resource_mcp", "exa_search_type", "neural"))
EXA_MAX_RESULTS = _config_int("resource_mcp", "exa_max_results", 8)
if os.getenv("EXA_MAX_RESULTS", "").strip().isdigit():
    EXA_MAX_RESULTS = int(os.getenv("EXA_MAX_RESULTS", "8"))
FIRECRAWL_API_KEY = os.getenv("FIRECRAWL_API_KEY", "")
FIRECRAWL_SCRAPE_URL = os.getenv("FIRECRAWL_SCRAPE_URL", "https://api.firecrawl.dev/v1/scrape")
FIRECRAWL_TIMEOUT_MILLISECONDS = _config_int("resource_mcp", "firecrawl_timeout_milliseconds", 15000)
if os.getenv("FIRECRAWL_TIMEOUT_MILLISECONDS", "").strip().isdigit():
    FIRECRAWL_TIMEOUT_MILLISECONDS = int(os.getenv("FIRECRAWL_TIMEOUT_MILLISECONDS", "15000"))

# Custom user model / 自定义用户模型
# 使用根目录下的users应用中的User模型
AUTH_USER_MODEL = "users.User"

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "zh-hans"

TIME_ZONE = "Asia/Shanghai"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media files
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# CORS settings
CORS_ALLOW_ALL_ORIGINS = DEBUG
CORS_ALLOWED_ORIGINS = _env_csv_list(
    "CORS_ALLOWED_ORIGINS",
    "https://edu.qintsg.xyz,http://edu.qintsg.xyz,http://127.0.0.1:3000,http://localhost:3000",
)
CSRF_TRUSTED_ORIGINS = _env_csv_list(
    "CSRF_TRUSTED_ORIGINS",
    "https://edu.qintsg.xyz,http://edu.qintsg.xyz,http://127.0.0.1:3000,http://localhost:3000",
)

# Django REST Framework settings
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "EXCEPTION_HANDLER": "common.utils.custom_exception_handler",
}

# JWT settings
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=2),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
}

# Authentication backends
# 支持用户名、邮箱或手机号登录
AUTHENTICATION_BACKENDS = [
    "users.backends.MultiFieldAuthBackend",
]

# DRF Spectacular settings
SPECTACULAR_SETTINGS = {
    "TITLE": "知识图谱驱动的个性化自适应学习系统 API",
    "DESCRIPTION": "知识图谱驱动的个性化自适应学习系统后端接口",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
}

# ============================================================================
# LLM大模型配置 / Large Language Model Configuration
# ============================================================================
# 支持的模型提供方：
# - 通义千问 / Qwen（DashScope OpenAI 兼容接口）
# - DeepSeek（OpenAI 兼容接口）
# - 豆包 / ModelArk（OpenAI 兼容接口）
# - 智谱 / GLM（OpenAI 兼容接口）
# - Kimi / Moonshot（OpenAI 兼容接口）
# - 自定义兼容网关（通过 LLM_API_FORMAT 描述接口格式）

LLM_PROVIDER = os.getenv(
    "LLM_PROVIDER",
    _config_value("llm", "provider", "deepseek"),
).strip().lower() or "deepseek"

# 默认使用的模型
LLM_MODEL = os.getenv(
    "LLM_MODEL",
    _config_value("llm", "model", "deepseek-v4-pro"),
).strip() or "deepseek-v4-pro"

# OpenAI 兼容网关描述
LLM_API_FORMAT = os.getenv(
    "LLM_API_FORMAT",
    _config_value("llm", "api_format", "openai-compatible"),
).strip().lower() or "openai-compatible"

LLM_REQUEST_TIMEOUT = _config_int(
    "llm",
    "request_timeout_seconds",
    _config_int("ai_services", "api_timeout", 120),
)
if os.getenv("LLM_REQUEST_TIMEOUT", "").strip().isdigit():
    LLM_REQUEST_TIMEOUT = int(os.getenv("LLM_REQUEST_TIMEOUT", "120"))

LLM_MAX_RETRIES = _config_int("llm", "max_retries", 2)
if os.getenv("LLM_MAX_RETRIES", "").strip().isdigit():
    LLM_MAX_RETRIES = int(os.getenv("LLM_MAX_RETRIES", "2"))

# 统一兼容网关地址（可选）
LLM_BASE_URL = os.getenv(
    "LLM_BASE_URL",
    _config_value("llm", "base_url", ""),
).strip()

# 非思考模式配置。默认关闭 reasoning/thinking，并通过 extra_body 兼容常见
# OpenAI 兼容网关的 enable_thinking=false 写法。
LLM_REASONING_ENABLED = _env_config_bool(
    "LLM_REASONING_ENABLED",
    "llm",
    "reasoning_enabled",
    False,
)
LLM_REASONING_EFFORT = os.getenv(
    "LLM_REASONING_EFFORT",
    _config_value("llm", "reasoning_effort", ""),
).strip().lower()
LLM_EXTRA_BODY = _config_json_dict("LLM_EXTRA_BODY_JSON", "llm", "extra_body_json")

# LLM 请求代理（可选）
LLM_HTTP_PROXY = os.getenv("LLM_HTTP_PROXY", os.getenv("HTTP_PROXY", "")).strip()
LLM_HTTPS_PROXY = os.getenv("LLM_HTTPS_PROXY", os.getenv("HTTPS_PROXY", "")).strip()

# 通用 / 自定义密钥入口（用于统一网关或自定义服务）
LLM_API_KEY = os.getenv("LLM_API_KEY", "")
CUSTOM_LLM_API_KEY = os.getenv("CUSTOM_LLM_API_KEY", "")
CUSTOM_LLM_BASE_URL = os.getenv("CUSTOM_LLM_BASE_URL", "")

# 通义千问API密钥（推荐）
DASHSCOPE_API_KEY = os.getenv("DASHSCOPE_API_KEY", "")
QWEN_BASE_URL = os.getenv("QWEN_BASE_URL", "")

# DeepSeek API密钥
DEEPSEEK_API_KEY = os.getenv("DEEPSEEK_API_KEY", "")
DEEPSEEK_BASE_URL = os.getenv("DEEPSEEK_BASE_URL", "")

# 豆包 / ModelArk 密钥与地址
ARK_API_KEY = os.getenv("ARK_API_KEY", "")
DOUBAO_API_KEY = os.getenv("DOUBAO_API_KEY", ARK_API_KEY)
DOUBAO_BASE_URL = os.getenv("DOUBAO_BASE_URL", "")

# 智谱 / GLM 密钥与地址
ZAI_API_KEY = os.getenv("ZAI_API_KEY", "")
ZHIPU_API_KEY = os.getenv("ZHIPU_API_KEY", ZAI_API_KEY)
ZHIPU_BASE_URL = os.getenv("ZHIPU_BASE_URL", "")

# Kimi / Moonshot 密钥与地址
MOONSHOT_API_KEY = os.getenv("MOONSHOT_API_KEY", "")
KIMI_API_KEY = os.getenv("KIMI_API_KEY", MOONSHOT_API_KEY)
KIMI_BASE_URL = os.getenv("KIMI_BASE_URL", "")

_llm_key = (
    LLM_API_KEY
    or CUSTOM_LLM_API_KEY
    or DASHSCOPE_API_KEY
    or DEEPSEEK_API_KEY
    or ARK_API_KEY
    or DOUBAO_API_KEY
    or ZAI_API_KEY
    or ZHIPU_API_KEY
    or MOONSHOT_API_KEY
    or KIMI_API_KEY
)
if not DEBUG and not _llm_key:
    import logging

    logging.warning("未配置LLM API密钥，AI功能将使用Mock响应。")
    logging.warning(
        "请设置 LLM_API_KEY，或配置 DASHSCOPE_API_KEY / DEEPSEEK_API_KEY / ARK_API_KEY / ZAI_API_KEY / MOONSHOT_API_KEY。"
    )

# File upload settings
FILE_UPLOAD_MAX_MEMORY_SIZE = 50 * 1024 * 1024  # 50MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 50 * 1024 * 1024  # 50MB

# ============================================================================
# 日志配置 / Logging Configuration
# ============================================================================
_LOG_DIR = BASE_DIR / "runtime_logs"
_LOG_DIR.mkdir(exist_ok=True)
(BASE_DIR / "runtime_logs" / "debug").mkdir(exist_ok=True)
(BASE_DIR / "runtime_logs" / "operations").mkdir(exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{asctime} [{levelname}] {name} | {message}",
            "style": "{",
            "datefmt": "%H:%M:%S",
        },
        "simple": {
            "format": "{asctime} [{levelname}] {name} | {message}",
            "style": "{",
            "datefmt": "%H:%M:%S",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
            "level": "INFO",
        },
        "debug_file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": str(_LOG_DIR / "debug" / "debug.log"),
            "maxBytes": 10 * 1024 * 1024,  # 10MB
            "backupCount": 5,
            "formatter": "verbose",
            "level": "DEBUG",
            "encoding": "utf-8",
        },
        "error_file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": str(_LOG_DIR / "debug" / "error.log"),
            "maxBytes": 10 * 1024 * 1024,
            "backupCount": 5,
            "formatter": "verbose",
            "level": "ERROR",
            "encoding": "utf-8",
        },
        "operation_file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": str(_LOG_DIR / "operations" / "operations.log"),
            "maxBytes": 10 * 1024 * 1024,
            "backupCount": 5,
            "formatter": "verbose",
            "level": "INFO",
            "encoding": "utf-8",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console", "debug_file", "error_file"],
            "level": "INFO",
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console", "error_file"],
            "level": "WARNING",
            "propagate": False,
        },
        # 应用模块日志：DEBUG级别输出到文件
        "users": {
            "handlers": ["console", "debug_file", "error_file"],
            "level": "INFO",
            "propagate": False,
        },
        "courses": {
            "handlers": ["console", "debug_file", "error_file"],
            "level": "INFO",
            "propagate": False,
        },
        "knowledge": {
            "handlers": ["console", "debug_file", "error_file"],
            "level": "INFO",
            "propagate": False,
        },
        "assessments": {
            "handlers": ["console", "debug_file", "error_file"],
            "level": "INFO",
            "propagate": False,
        },
        "learning": {
            "handlers": ["console", "debug_file", "error_file"],
            "level": "INFO",
            "propagate": False,
        },
        "exams": {
            "handlers": ["console", "debug_file", "error_file"],
            "level": "INFO",
            "propagate": False,
        },
        "ai_services": {
            "handlers": ["console", "debug_file", "error_file"],
            "level": "INFO",
            "propagate": False,
        },
        "logs": {
            "handlers": ["console", "operation_file"],
            "level": "INFO",
            "propagate": False,
        },
        "common": {
            "handlers": ["console", "debug_file", "error_file"],
            "level": "INFO",
            "propagate": False,
        },
        "httpx": {
            "handlers": ["debug_file", "error_file"],
            "level": "WARNING",
            "propagate": False,
        },
        "httpcore": {
            "handlers": ["debug_file", "error_file"],
            "level": "WARNING",
            "propagate": False,
        },
        "urllib3": {
            "handlers": ["debug_file", "error_file"],
            "level": "WARNING",
            "propagate": False,
        },
    },
    "root": {
        "handlers": ["console", "debug_file"],
        "level": "INFO",
    },
}
