"""
Django settings for wisdom_edu_api project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import configparser
import json
import os
from datetime import timedelta
from dotenv import load_dotenv

from .settings_ai import load_ai_settings

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")

CONFIG_INI_PATH = BASE_DIR / "config.ini"
_settings_config = configparser.ConfigParser()
if CONFIG_INI_PATH.exists():
    _settings_config.read(CONFIG_INI_PATH, encoding="utf-8")


def _config_value(section: str, key: str, default: str = "") -> str:
    """从 config.ini 读取字符串配置，为环境变量缺省值提供回退。"""
    try:
        return _settings_config.get(section, key)
    except (configparser.NoSectionError, configparser.NoOptionError):
        return default


def _config_int(section: str, key: str, default: int) -> int:
    """从 config.ini 读取整数配置，为运行时参数提供稳定回退。"""
    raw_value = _config_value(section, key, str(default)).strip()
    if raw_value.isdigit():
        return int(raw_value)
    return default


def _config_bool(section: str, key: str, default: bool) -> bool:
    """从 config.ini 读取布尔配置，兼容常见 true/false 写法。"""
    raw_value = _config_value(section, key, str(default)).strip().lower()
    if raw_value in {"1", "true", "yes", "on"}:
        return True
    if raw_value in {"0", "false", "no", "off"}:
        return False
    return default


def _env_config_bool(env_name: str, section: str, key: str, default: bool) -> bool:
    """读取环境变量优先的布尔配置。"""
    raw_value = os.getenv(env_name, "").strip().lower()
    if raw_value in {"1", "true", "yes", "on"}:
        return True
    if raw_value in {"0", "false", "no", "off"}:
        return False
    return _config_bool(section, key, default)


def _config_json_dict(env_name: str, section: str, key: str) -> dict[str, object]:
    """读取 JSON 字典配置，解析失败时返回空字典避免启动中断。"""
    raw_value = os.getenv(env_name, _config_value(section, key, "{}")).strip()
    if not raw_value:
        return {}
    try:
        parsed = json.loads(raw_value)
    except json.JSONDecodeError:
        return {}
    return parsed if isinstance(parsed, dict) else {}


def _env_csv_list(env_name: str, default: str = "") -> list[str]:
    """按逗号解析环境变量列表，并自动去除空白与空项。"""
    raw_value = os.getenv(env_name, default)
    if not raw_value:
        return []
    return [item.strip() for item in raw_value.split(",") if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "SECRET_KEY", "django-insecure-wul(tlxm%wjk^qz0#o1xlf_94ic9!f(mz$_-f5vn)s#fpnhy#3"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "True").lower() == "true"

ALLOWED_HOSTS = _env_csv_list(
    "ALLOWED_HOSTS",
    "localhost,127.0.0.1,edu.qintsg.xyz,edu.qintsg.cn,47.103.44.104,106.14.209.7",
) or ["localhost", "127.0.0.1"]

USE_X_FORWARDED_HOST = os.getenv("USE_X_FORWARDED_HOST", "True").lower() == "true"
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# Application definition

INSTALLED_APPS = [
    "daphne",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party apps / 第三方应用
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
    "django_filters",
    "drf_spectacular",
    "channels",
    # Local apps / 本地应用（使用Django startapp创建）
    "users",  # 用户模块：认证、权限、偏好
    "courses",  # 课程模块：课程、班级、选课
    "knowledge",  # 知识图谱模块：知识点、关系、资源
    "assessments",  # 测评模块：题库、测评、能力评分
    "learning",  # 学习路径模块：路径、节点、进度
    "exams",  # 考试模块：考试、提交、反馈报告
    "ai_services",  # AI服务模块：大模型调用日志
    "logs",  # 操作日志模块：系统操作日志记录
    "common",  # 公共模块：工具函数、权限类
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # 操作日志中间件（记录API操作日志）
    "logs.middleware.OperationLogMiddleware",
]

ROOT_URLCONF = "wisdom_edu_api.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "wisdom_edu_api.wsgi.application"
ASGI_APPLICATION = "wisdom_edu_api.asgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME", "wisdom_edu"),
        "USER": os.getenv("DB_USER", "wisdom"),
        "PASSWORD": os.getenv("DB_PASSWORD", "wisdom123"),
        "HOST": os.getenv("DB_HOST", "127.0.0.1"),
        "PORT": os.getenv("DB_PORT", "5432"),
    }
}

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    }
}

globals().update(
    load_ai_settings(
        _config_value,
        _config_int,
        _env_config_bool,
        _config_json_dict,
        DEBUG,
    )
)

# Custom user model / 自定义用户模型
# 使用根目录下的users应用中的User模型
AUTH_USER_MODEL = "users.User"

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "zh-hans"

TIME_ZONE = "Asia/Shanghai"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media files
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# CORS settings
CORS_ALLOW_ALL_ORIGINS = DEBUG
CORS_ALLOWED_ORIGINS = _env_csv_list(
    "CORS_ALLOWED_ORIGINS",
    "https://edu.qintsg.xyz,http://edu.qintsg.xyz,https://edu.qintsg.cn,http://edu.qintsg.cn,http://127.0.0.1:3000,http://localhost:3000",
)
CSRF_TRUSTED_ORIGINS = _env_csv_list(
    "CSRF_TRUSTED_ORIGINS",
    "https://edu.qintsg.xyz,http://edu.qintsg.xyz,https://edu.qintsg.cn,http://edu.qintsg.cn,http://127.0.0.1:3000,http://localhost:3000",
)

# Django REST Framework settings
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "EXCEPTION_HANDLER": "common.utils.custom_exception_handler",
}

# JWT settings
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=2),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
}

# Authentication backends
# 支持用户名、邮箱或手机号登录
AUTHENTICATION_BACKENDS = [
    "users.backends.MultiFieldAuthBackend",
]

# DRF Spectacular settings
SPECTACULAR_SETTINGS = {
    "TITLE": "知识图谱驱动的个性化自适应学习系统 API",
    "DESCRIPTION": "知识图谱驱动的个性化自适应学习系统后端接口",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
}

# File upload settings
FILE_UPLOAD_MAX_MEMORY_SIZE = 50 * 1024 * 1024  # 50MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 50 * 1024 * 1024  # 50MB

# ============================================================================
# 日志配置 / Logging Configuration
# ============================================================================
_LOG_DIR = BASE_DIR / "runtime_logs"
_LOG_DIR.mkdir(exist_ok=True)
(BASE_DIR / "runtime_logs" / "debug").mkdir(exist_ok=True)
(BASE_DIR / "runtime_logs" / "operations").mkdir(exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{asctime} [{levelname}] {name} | {message}",
            "style": "{",
            "datefmt": "%H:%M:%S",
        },
        "simple": {
            "format": "{asctime} [{levelname}] {name} | {message}",
            "style": "{",
            "datefmt": "%H:%M:%S",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
            "level": "INFO",
        },
        "debug_file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": str(_LOG_DIR / "debug" / "debug.log"),
            "maxBytes": 10 * 1024 * 1024,  # 10MB
            "backupCount": 5,
            "formatter": "verbose",
            "level": "DEBUG",
            "encoding": "utf-8",
        },
        "error_file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": str(_LOG_DIR / "debug" / "error.log"),
            "maxBytes": 10 * 1024 * 1024,
            "backupCount": 5,
            "formatter": "verbose",
            "level": "ERROR",
            "encoding": "utf-8",
        },
        "operation_file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": str(_LOG_DIR / "operations" / "operations.log"),
            "maxBytes": 10 * 1024 * 1024,
            "backupCount": 5,
            "formatter": "verbose",
            "level": "INFO",
            "encoding": "utf-8",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console", "debug_file", "error_file"],
            "level": "INFO",
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console", "error_file"],
            "level": "WARNING",
            "propagate": False,
        },
        # 应用模块日志：DEBUG级别输出到文件
        "users": {
            "handlers": ["console", "debug_file", "error_file"],
            "level": "INFO",
            "propagate": False,
        },
        "courses": {
            "handlers": ["console", "debug_file", "error_file"],
            "level": "INFO",
            "propagate": False,
        },
        "knowledge": {
            "handlers": ["console", "debug_file", "error_file"],
            "level": "INFO",
            "propagate": False,
        },
        "assessments": {
            "handlers": ["console", "debug_file", "error_file"],
            "level": "INFO",
            "propagate": False,
        },
        "learning": {
            "handlers": ["console", "debug_file", "error_file"],
            "level": "INFO",
            "propagate": False,
        },
        "exams": {
            "handlers": ["console", "debug_file", "error_file"],
            "level": "INFO",
            "propagate": False,
        },
        "ai_services": {
            "handlers": ["console", "debug_file", "error_file"],
            "level": "INFO",
            "propagate": False,
        },
        "logs": {
            "handlers": ["console", "operation_file"],
            "level": "INFO",
            "propagate": False,
        },
        "common": {
            "handlers": ["console", "debug_file", "error_file"],
            "level": "INFO",
            "propagate": False,
        },
        "httpx": {
            "handlers": ["debug_file", "error_file"],
            "level": "WARNING",
            "propagate": False,
        },
        "httpcore": {
            "handlers": ["debug_file", "error_file"],
            "level": "WARNING",
            "propagate": False,
        },
        "urllib3": {
            "handlers": ["debug_file", "error_file"],
            "level": "WARNING",
            "propagate": False,
        },
    },
    "root": {
        "handlers": ["console", "debug_file"],
        "level": "INFO",
    },
}
