# Generated by Django 6.0.1 on 2026-01-20 02:24

from django.db import migrations, models


# 定义数据库迁移操作，Django 将按顺序执行以下变更
class Migration(migrations.Migration):

    # 标记为初始迁移，首次创建该应用的数据库表
    initial = True

    # 声明依赖的先前迁移版本
    dependencies = [
    ]

    # 要执行的数据库操作列表
    operations = [
        # 创建数据表模型
        migrations.CreateModel(
            # 模型名称: Class
            name='Class',
            # 字段定义列表
            fields=[
                # id: ID (自增主键)
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # name: 班级名称 (字符串字段)
                ('name', models.CharField(help_text='如：2024级计算机1班', max_length=200, verbose_name='班级名称')),
                # semester: 学期 (字符串字段)
                ('semester', models.CharField(blank=True, max_length=50, null=True, verbose_name='学期')),
                # created_at: 创建时间 (日期时间字段)
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            # 模型的 Meta 配置选项
            options={
                'verbose_name': '班级',
                'verbose_name_plural': '班级',
                'db_table': 'classes',
            },
        ),
        # 创建数据表模型
        migrations.CreateModel(
            # 模型名称: Course
            name='Course',
            # 字段定义列表
            fields=[
                # id: ID (自增主键)
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # name: 课程名称 (字符串字段)
                ('name', models.CharField(help_text='课程的完整名称', max_length=200, verbose_name='课程名称')),
                # description: 课程描述 (长文本字段)
                ('description', models.TextField(blank=True, help_text='课程的详细介绍', null=True, verbose_name='课程描述')),
                # cover: 封面图片 (图片字段)
                ('cover', models.ImageField(blank=True, null=True, upload_to='course_covers/', verbose_name='封面图片')),
                # term: 学期 (字符串字段)
                ('term', models.CharField(blank=True, help_text='如：2024春季学期', max_length=50, null=True, verbose_name='学期')),
                # created_at: 创建时间 (日期时间字段)
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                # updated_at: 更新时间 (日期时间字段)
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            # 模型的 Meta 配置选项
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
                'db_table': 'courses',
                'ordering': ['-created_at'],
            },
        ),
        # 创建数据表模型
        migrations.CreateModel(
            # 模型名称: Enrollment
            name='Enrollment',
            # 字段定义列表
            fields=[
                # id: ID (自增主键)
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # role: 班级角色 (字符串字段)
                ('role', models.CharField(choices=[('student', '学生'), ('assistant', '助教')], default='student', max_length=20, verbose_name='班级角色')),
                # enrolled_at: 加入时间 (日期时间字段)
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
            ],
            # 模型的 Meta 配置选项
            options={
                'verbose_name': '选课记录',
                'verbose_name_plural': '选课记录',
                'db_table': 'enrollments',
            },
        ),
    ]
