# Generated by Django 6.0.1 on 2026-01-20 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


# 定义数据库迁移操作，Django 将按顺序执行以下变更
class Migration(migrations.Migration):

    # 标记为初始迁移，首次创建该应用的数据库表
    initial = True

    # 声明依赖的先前迁移版本
    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # 要执行的数据库操作列表
    operations = [
        # 添加新字段
        migrations.AddField(
            # 目标模型: class
            model_name='class',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_classes', to=settings.AUTH_USER_MODEL, verbose_name='授课教师'),
        ),
        # 添加新字段
        migrations.AddField(
            # 目标模型: course
            model_name='course',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_courses', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        # 添加新字段
        migrations.AddField(
            # 目标模型: class
            model_name='class',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='courses.course', verbose_name='所属课程'),
        ),
        # 添加新字段
        migrations.AddField(
            # 目标模型: enrollment
            model_name='enrollment',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.class', verbose_name='班级'),
        ),
        # 添加新字段
        migrations.AddField(
            # 目标模型: enrollment
            model_name='enrollment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        # 修改联合唯一约束
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('user', 'class_obj')},
        ),
    ]
