# Generated by Django 6.0.1 on 2026-01-21 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


# 定义数据库迁移操作，Django 将按顺序执行以下变更
class Migration(migrations.Migration):

    # 声明依赖的先前迁移版本
    dependencies = [
        ('courses', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # 要执行的数据库操作列表
    operations = [
        # 修改模型元数据选项
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['-created_at'], 'verbose_name': '班级', 'verbose_name_plural': '班级'},
        ),
        # 添加新字段
        migrations.AddField(
            # 目标模型: class
            model_name='class',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='班级描述'),
        ),
        # 添加新字段
        migrations.AddField(
            # 目标模型: class
            model_name='class',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否激活'),
        ),
        # 添加新字段
        migrations.AddField(
            # 目标模型: class
            model_name='class',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        # 添加新字段
        migrations.AddField(
            # 目标模型: course
            model_name='course',
            name='initial_assessment_count',
            field=models.IntegerField(default=10, help_text='学生进入课程时随机抽取的初始评测题目数量', verbose_name='初始评测题目数量'),
        ),
        # 添加新字段
        migrations.AddField(
            # 目标模型: course
            model_name='course',
            name='is_public',
            field=models.BooleanField(default=True, help_text='公开课程对所有教师可见，可发布到班级', verbose_name='是否公开'),
        ),
        # 修改字段属性
        migrations.AlterField(
            # 目标模型: class
            model_name='class',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='courses.course', verbose_name='默认课程'),
        ),
        # 创建数据表模型
        migrations.CreateModel(
            # 模型名称: ClassCourse
            name='ClassCourse',
            # 字段定义列表
            fields=[
                # id: ID (自增主键)
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # is_active: 是否激活 (布尔字段)
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                # published_at: 发布时间 (日期时间字段)
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                # class_obj: 班级 (外键关联)
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_courses', to='courses.class', verbose_name='班级')),
                # course: 课程 (外键关联)
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_courses', to='courses.course', verbose_name='课程')),
                # published_by: 发布者 (外键关联)
                ('published_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_class_courses', to=settings.AUTH_USER_MODEL, verbose_name='发布者')),
            ],
            # 模型的 Meta 配置选项
            options={
                'verbose_name': '班级课程',
                'verbose_name_plural': '班级课程',
                'db_table': 'class_courses',
                'unique_together': {('class_obj', 'course')},
            },
        ),
    ]
