# Generated by Django 6.0.2 on 2026-02-19 10:19

from django.db import migrations, models


# 定义数据库迁移操作，Django 将按顺序执行以下变更
class Migration(migrations.Migration):

    # 声明依赖的先前迁移版本
    dependencies = [
        ('courses', '0003_alter_class_options_class_description_and_more'),
    ]

    # 要执行的数据库操作列表
    operations = [
        # 添加新字段
        migrations.AddField(
            # 目标模型: course
            model_name='course',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='存储考试配置、课程管理等自定义参数。例：{"exam_pass_score": 60, "exam_duration": 90, "allow_retake": true, "max_retake_times": 3, "resource_approval": false}', verbose_name='课程配置'),
        ),
    ]
