# Generated by Django 6.0.2 on 2026-02-19 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


# 定义数据库迁移操作，Django 将按顺序执行以下变更
class Migration(migrations.Migration):

    # 声明依赖的先前迁移版本
    dependencies = [
        ('courses', '0004_course_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # 要执行的数据库操作列表
    operations = [
        # 创建数据表模型
        migrations.CreateModel(
            # 模型名称: Announcement
            name='Announcement',
            # 字段定义列表
            fields=[
                # id: ID (自增主键)
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # title: 公告标题 (字符串字段)
                ('title', models.CharField(max_length=200, verbose_name='公告标题')),
                # content: 公告内容 (长文本字段)
                ('content', models.TextField(verbose_name='公告内容')),
                # created_at: 发布时间 (日期时间字段)
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                # updated_at: 更新时间 (日期时间字段)
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                # class_obj: 班级 (外键关联)
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='courses.class', verbose_name='班级')),
                # created_by: 发布者 (外键关联)
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to=settings.AUTH_USER_MODEL, verbose_name='发布者')),
            ],
            # 模型的 Meta 配置选项
            options={
                'verbose_name': '班级公告',
                'verbose_name_plural': '班级公告',
                'db_table': 'announcements',
                'ordering': ['-created_at'],
            },
        ),
    ]
