# Generated by Django 6.0.1 on 2026-01-20 02:24

from django.db import migrations, models


# 定义数据库迁移操作，Django 将按顺序执行以下变更
class Migration(migrations.Migration):

    # 标记为初始迁移，首次创建该应用的数据库表
    initial = True

    # 声明依赖的先前迁移版本
    dependencies = [
    ]

    # 要执行的数据库操作列表
    operations = [
        # 创建数据表模型
        migrations.CreateModel(
            # 模型名称: LLMCallLog
            name='LLMCallLog',
            # 字段定义列表
            fields=[
                # id: ID (自增主键)
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # call_type: 调用类型 (字符串字段)
                ('call_type', models.CharField(choices=[('profile_analysis', '画像诊断'), ('path_planning', '路径规划'), ('resource_reason', '资源推荐'), ('feedback_report', '反馈报告'), ('other', '其他')], max_length=30, verbose_name='调用类型')),
                # input_summary: 输入摘要 (长文本字段)
                ('input_summary', models.TextField(blank=True, null=True, verbose_name='输入摘要')),
                # output_summary: 输出摘要 (长文本字段)
                ('output_summary', models.TextField(blank=True, null=True, verbose_name='输出摘要')),
                # model: 模型 (字符串字段)
                ('model', models.CharField(blank=True, help_text='如: qwen-plus, deepseek-chat', max_length=50, null=True, verbose_name='模型')),
                # tokens_used: Token用量 (整数字段)
                ('tokens_used', models.IntegerField(blank=True, null=True, verbose_name='Token用量')),
                # duration_ms: 耗时(毫秒) (整数字段)
                ('duration_ms', models.IntegerField(blank=True, null=True, verbose_name='耗时(毫秒)')),
                # is_success: 是否成功 (布尔字段)
                ('is_success', models.BooleanField(default=True, verbose_name='是否成功')),
                # error_message: 错误信息 (长文本字段)
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                # created_at: 调用时间 (日期时间字段)
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='调用时间')),
            ],
            # 模型的 Meta 配置选项
            options={
                'verbose_name': 'LLM调用日志',
                'verbose_name_plural': 'LLM调用日志',
                'db_table': 'llm_call_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
