# Generated by Django 6.0.2 on 2026-02-18 15:05

from django.db import migrations, models


# 定义数据库迁移操作，Django 将按顺序执行以下变更
class Migration(migrations.Migration):

    # 声明依赖的先前迁移版本
    dependencies = [
        ('ai_services', '0002_initial'),
    ]

    # 要执行的数据库操作列表
    operations = [
        # 修改字段属性
        migrations.AlterField(
            # 目标模型: llmcalllog
            model_name='llmcalllog',
            name='call_type',
            field=models.CharField(choices=[('profile_analysis', '画像诊断'), ('path_planning', '路径规划'), ('resource_reason', '资源推荐'), ('feedback_report', '反馈报告'), ('chat', 'AI对话'), ('node_intro', '知识点介绍'), ('kt_analysis', 'KT分析'), ('resource_recommend', '资源推荐(AI)'), ('other', '其他')], max_length=30, verbose_name='调用类型'),
        ),
    ]
