# Generated by Django 6.0.4 on 2026-05-03 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_services", "0003_add_chat_kt_call_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="llmcalllog",
            name="model",
            field=models.CharField(
                blank=True,
                help_text="如: deepseek-v4-flash, deepseek-chat, qwen-plus",
                max_length=50,
                null=True,
                verbose_name="模型",
            ),
        ),
    ]
