# Generated by Django 6.0.1 on 2026-01-20 02:24

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


# 定义数据库迁移操作，Django 将按顺序执行以下变更
class Migration(migrations.Migration):

    # 标记为初始迁移，首次创建该应用的数据库表
    initial = True

    # 声明依赖的先前迁移版本
    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('courses', '0001_initial'),
    ]

    # 要执行的数据库操作列表
    operations = [
        # 创建数据表模型
        migrations.CreateModel(
            # 模型名称: User
            name='User',
            # 字段定义列表
            fields=[
                # id: ID (自增主键)
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # password: password (字符串字段)
                ('password', models.CharField(max_length=128, verbose_name='password')),
                # last_login: last login (日期时间字段)
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                # is_superuser: superuser status (布尔字段)
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                # username: username (字符串字段)
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                # first_name: first name (字符串字段)
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                # last_name: last name (字符串字段)
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                # email: email address (邮箱字段)
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                # is_staff: staff status (布尔字段)
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                # is_active: active (布尔字段)
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                # date_joined: date joined (日期时间字段)
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                # role: 角色 (字符串字段)
                ('role', models.CharField(choices=[('student', '学生'), ('teacher', '教师'), ('admin', '管理员')], default='student', help_text='用户在系统中的角色', max_length=20, verbose_name='角色')),
                # avatar: 头像 (图片字段)
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='头像')),
                # phone: 手机号 (字符串字段)
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号')),
                # groups: groups (多对多关联)
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                # user_permissions: user permissions (多对多关联)
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            # 模型的 Meta 配置选项
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        # 创建数据表模型
        migrations.CreateModel(
            # 模型名称: HabitPreference
            name='HabitPreference',
            # 字段定义列表
            fields=[
                # id: ID (自增主键)
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # preferred_resource: 偏好资源类型 (字符串字段)
                ('preferred_resource', models.CharField(choices=[('video', '视频'), ('document', '文档'), ('exercise', '练习'), ('link', '外部链接')], default='video', max_length=50, verbose_name='偏好资源类型')),
                # preferred_study_time: 高效学习时间 (字符串字段)
                ('preferred_study_time', models.CharField(choices=[('morning', '早上 (6:00-12:00)'), ('afternoon', '下午 (12:00-18:00)'), ('evening', '晚上 (18:00-24:00)'), ('night', '深夜 (0:00-6:00)')], default='evening', max_length=50, verbose_name='高效学习时间')),
                # preferences: 其他偏好 (JSON 数据字段)
                ('preferences', models.JSONField(default=dict, help_text='存储其他个性化偏好设置', verbose_name='其他偏好')),
                # updated_at: 更新时间 (日期时间字段)
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                # user: 用户 (一对一关联)
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='habit_preference', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            # 模型的 Meta 配置选项
            options={
                'verbose_name': '学习习惯偏好',
                'verbose_name_plural': '学习习惯偏好',
                'db_table': 'habit_preferences',
            },
        ),
        # 创建数据表模型
        migrations.CreateModel(
            # 模型名称: UserCourseContext
            name='UserCourseContext',
            # 字段定义列表
            fields=[
                # id: ID (自增主键)
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # updated_at: 更新时间 (日期时间字段)
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                # current_class: 当前班级 (外键关联)
                ('current_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='courses.class', verbose_name='当前班级')),
                # current_course: 当前课程 (外键关联)
                ('current_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='courses.course', verbose_name='当前课程')),
                # user: 用户 (一对一关联)
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='course_context', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            # 模型的 Meta 配置选项
            options={
                'verbose_name': '用户课程上下文',
                'verbose_name_plural': '用户课程上下文',
                'db_table': 'user_course_context',
            },
        ),
    ]
