# Generated by Django 6.0.1 on 2026-01-21 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


# 定义数据库迁移操作，Django 将按顺序执行以下变更
class Migration(migrations.Migration):

    # 声明依赖的先前迁移版本
    dependencies = [
        ('courses', '0003_alter_class_options_class_description_and_more'),
        ('users', '0001_initial'),
    ]

    # 要执行的数据库操作列表
    operations = [
        # 添加新字段
        migrations.AddField(
            # 目标模型: habitpreference
            model_name='habitpreference',
            name='accept_challenge',
            field=models.BooleanField(default=True, help_text='是否愿意尝试难度较高的内容', verbose_name='接受挑战性内容'),
        ),
        # 添加新字段
        migrations.AddField(
            # 目标模型: habitpreference
            model_name='habitpreference',
            name='daily_goal_minutes',
            field=models.IntegerField(default=60, verbose_name='每日学习目标(分钟)'),
        ),
        # 添加新字段
        migrations.AddField(
            # 目标模型: habitpreference
            model_name='habitpreference',
            name='learning_style',
            field=models.CharField(choices=[('visual', '视觉型（图表、图片）'), ('auditory', '听觉型（讲解、音频）'), ('reading', '阅读型（文字阅读）'), ('kinesthetic', '动手型（练习、实践）')], default='visual', max_length=50, verbose_name='学习风格'),
        ),
        # 添加新字段
        migrations.AddField(
            # 目标模型: habitpreference
            model_name='habitpreference',
            name='reminder_settings',
            field=models.JSONField(default=dict, help_text='学习提醒相关设置', verbose_name='提醒设置'),
        ),
        # 添加新字段
        migrations.AddField(
            # 目标模型: habitpreference
            model_name='habitpreference',
            name='review_frequency',
            field=models.CharField(choices=[('daily', '每日复习'), ('weekly', '每周复习'), ('before_exam', '考前复习'), ('never', '很少复习')], default='weekly', max_length=50, verbose_name='复习频率'),
        ),
        # 添加新字段
        migrations.AddField(
            # 目标模型: habitpreference
            model_name='habitpreference',
            name='study_duration',
            field=models.CharField(choices=[('short', '短时间（15-30分钟）'), ('medium', '中等（30-60分钟）'), ('long', '长时间（60分钟以上）')], default='medium', max_length=50, verbose_name='单次学习时长'),
        ),
        # 添加新字段
        migrations.AddField(
            # 目标模型: habitpreference
            model_name='habitpreference',
            name='study_pace',
            field=models.CharField(choices=[('fast', '快节奏（快速浏览）'), ('moderate', '中等节奏'), ('slow', '慢节奏（深度学习）'), ('adaptive', '自适应')], default='moderate', max_length=50, verbose_name='学习节奏'),
        ),
        # 添加新字段
        migrations.AddField(
            # 目标模型: habitpreference
            model_name='habitpreference',
            name='weekly_goal_days',
            field=models.IntegerField(default=5, verbose_name='每周学习目标(天)'),
        ),
        # 添加新字段
        migrations.AddField(
            # 目标模型: user
            model_name='user',
            name='real_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='真实姓名'),
        ),
        # 添加新字段
        migrations.AddField(
            # 目标模型: user
            model_name='user',
            name='student_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='学号/工号'),
        ),
        # 修改字段属性
        migrations.AlterField(
            # 目标模型: habitpreference
            model_name='habitpreference',
            name='preferred_resource',
            field=models.CharField(choices=[('video', '视频'), ('document', '文档'), ('exercise', '练习'), ('link', '外部链接'), ('mixed', '混合')], default='video', max_length=50, verbose_name='偏好资源类型'),
        ),
        # 修改字段属性
        migrations.AlterField(
            # 目标模型: habitpreference
            model_name='habitpreference',
            name='preferred_study_time',
            field=models.CharField(choices=[('morning', '早上 (6:00-12:00)'), ('afternoon', '下午 (12:00-18:00)'), ('evening', '晚上 (18:00-24:00)'), ('night', '深夜 (0:00-6:00)'), ('flexible', '灵活安排')], default='evening', max_length=50, verbose_name='高效学习时间'),
        ),
        # 修改字段属性
        migrations.AlterField(
            # 目标模型: user
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号'),
        ),
        # 创建数据表模型
        migrations.CreateModel(
            # 模型名称: ActivationCode
            name='ActivationCode',
            # 字段定义列表
            fields=[
                # id: ID (自增主键)
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # code: 激活码 (字符串字段)
                ('code', models.CharField(help_text='8位随机激活码', max_length=20, unique=True, verbose_name='激活码')),
                # code_type: 类型 (字符串字段)
                ('code_type', models.CharField(choices=[('teacher', '教师激活码'), ('admin', '管理员激活码')], default='teacher', max_length=20, verbose_name='类型')),
                # is_used: 是否已使用 (布尔字段)
                ('is_used', models.BooleanField(default=False, verbose_name='是否已使用')),
                # used_at: 使用时间 (日期时间字段)
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='使用时间')),
                # expires_at: 过期时间 (日期时间字段)
                ('expires_at', models.DateTimeField(blank=True, help_text='为空表示永不过期', null=True, verbose_name='过期时间')),
                # remark: 备注 (字符串字段)
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                # created_at: 创建时间 (日期时间字段)
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                # created_by: 创建者 (外键关联)
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_activation_codes', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                # used_by: 使用者 (外键关联)
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_activation_codes', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            # 模型的 Meta 配置选项
            options={
                'verbose_name': '激活码',
                'verbose_name_plural': '激活码',
                'db_table': 'activation_codes',
                'ordering': ['-created_at'],
            },
        ),
        # 创建数据表模型
        migrations.CreateModel(
            # 模型名称: ClassInvitation
            name='ClassInvitation',
            # 字段定义列表
            fields=[
                # id: ID (自增主键)
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # code: 邀请码 (字符串字段)
                ('code', models.CharField(help_text='6位随机邀请码', max_length=20, unique=True, verbose_name='邀请码')),
                # max_uses: 最大使用次数 (整数字段)
                ('max_uses', models.IntegerField(default=0, help_text='0表示无限制', verbose_name='最大使用次数')),
                # use_count: 已使用次数 (整数字段)
                ('use_count', models.IntegerField(default=0, verbose_name='已使用次数')),
                # expires_at: 过期时间 (日期时间字段)
                ('expires_at', models.DateTimeField(blank=True, help_text='为空表示永不过期', null=True, verbose_name='过期时间')),
                # is_active: 是否激活 (布尔字段)
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                # created_at: 创建时间 (日期时间字段)
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                # class_obj: 班级 (外键关联)
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='courses.class', verbose_name='班级')),
                # created_by: 创建者 (外键关联)
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invitations', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            # 模型的 Meta 配置选项
            options={
                'verbose_name': '班级邀请码',
                'verbose_name_plural': '班级邀请码',
                'db_table': 'class_invitations',
                'ordering': ['-created_at'],
            },
        ),
    ]
