# Generated by Django 6.0.2 on 2026-02-19 04:27

from django.db import migrations, models


# 定义数据库迁移操作，Django 将按顺序执行以下变更
class Migration(migrations.Migration):

    # 声明依赖的先前迁移版本
    dependencies = [
        ('users', '0002_habitpreference_accept_challenge_and_more'),
    ]

    # 要执行的数据库操作列表
    operations = [
        # 修改字段属性
        migrations.AlterField(
            # 目标模型: user
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, help_text='可选，用于登录和找回密码', max_length=254, null=True, unique=True, verbose_name='邮箱'),
        ),
        # 修改字段属性
        migrations.AlterField(
            # 目标模型: user
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='可选，用于登录', max_length=11, null=True, unique=True, verbose_name='手机号'),
        ),
    ]
