# Generated by Django 6.0.2 on 2026-02-19 05:25

from django.db import migrations, models


# 定义数据库迁移操作，Django 将按顺序执行以下变更
class Migration(migrations.Migration):

    # 声明依赖的先前迁移版本
    dependencies = [
        ('users', '0003_alter_user_email_alter_user_phone'),
    ]

    # 要执行的数据库操作列表
    operations = [
        # 修改字段属性
        migrations.AlterField(
            # 目标模型: habitpreference
            model_name='habitpreference',
            name='review_frequency',
            field=models.CharField(choices=[('daily', '每日复习'), ('weekly', '每周复习'), ('before_exam', '考前复习'), ('spaced', '间隔复习（记忆曲线）'), ('never', '很少复习')], default='weekly', max_length=50, verbose_name='复习频率'),
        ),
    ]
