# Generated by Django 6.0.2 on 2026-02-19 10:19

from django.db import migrations


# 定义数据库迁移操作，Django 将按顺序执行以下变更
class Migration(migrations.Migration):

    # 声明依赖的先前迁移版本
    dependencies = [
        ('users', '0004_alter_habitpreference_review_frequency'),
    ]

    # 要执行的数据库操作列表
    operations = [
        # 删除字段
        migrations.RemoveField(
            # 目标模型: habitpreference
            model_name='habitpreference',
            name='reminder_settings',
        ),
    ]
