# Generated by Django 6.0.4 on 2026-05-09 08:00

import users.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_habitpreference_reminder_settings"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", users.managers.OptionalContactUserManager()),
            ],
        ),
    ]
